import type { SchengenMember } from './types';

export const SCHENGEN_MEMBERS: SchengenMember[] = [
  { flag: '🇦🇹', name: 'Avusturya' },
  { flag: '🇧🇪', name: 'Belçika' },
  { flag: '🇧🇬', name: 'Bulgaristan' },
  { flag: '🇭🇷', name: 'Hırvatistan' },
  { flag: '🇨🇿', name: 'Çekya' },
  { flag: '🇩🇰', name: 'Danimarka' },
  { flag: '🇪🇪', name: 'Estonya' },
  { flag: '🇫🇮', name: 'Finlandiya' },
  { flag: '🇫🇷', name: 'Fransa' },
  { flag: '🇩🇪', name: 'Almanya' },
  { flag: '🇬🇷', name: 'Yunanistan' },
  { flag: '🇭🇺', name: 'Macaristan' },
  { flag: '🇮🇸', name: 'İzlanda' },
  { flag: '🇮🇹', name: 'İtalya' },
  { flag: '🇱🇻', name: 'Letonya' },
  { flag: '🇱🇮', name: 'Lihtenştayn' },
  { flag: '🇱🇹', name: 'Litvanya' },
  { flag: '🇱🇺', name: 'Lüksemburg' },
  { flag: '🇲🇹', name: 'Malta' },
  { flag: '🇳🇱', name: 'Hollanda' },
  { flag: '🇳🇴', name: 'Norveç' },
  { flag: '🇵🇱', name: 'Polonya' },
  { flag: '🇵🇹', name: 'Portekiz' },
  { flag: '🇷🇴', name: 'Romanya' },
  { flag: '🇸🇰', name: 'Slovakya' },
  { flag: '🇸🇮', name: 'Slovenya' },
  { flag: '🇪🇸', name: 'İspanya' },
  { flag: '🇸🇪', name: 'İsveç' },
  { flag: '🇨🇭', name: 'İsviçre' },
];

export const SCHENGEN_REJECTION_REASONS = [
  { title: 'Geri dönme niyetinden şüphe',   desc: 'Ev ülkesiyle bağın yetersiz kanıtı — istihdam, mülk, aile.' },
  { title: 'Tutarsız güzergah',             desc: 'Seyahatin belirtilen amacıyla örtüşmeyen otel ve uçuş tarihleri.' },
  { title: 'Yetersiz mali güç',             desc: 'Banka bakiyesi seyahati ve yedek fonu karşılayacak düzeyde değil.' },
  { title: 'Sigortanın eşiğin altında',     desc: '30.000 Euro\'nun altında veya Schengen bölgesini kapsamayan seyahat sigortası.' },
  { title: 'Geçmiş süre aşımı veya ihlal', desc: 'Önceki Schengen ihlalleri kapak mektubunda açıkça ele alınmalıdır.' },
];
