-- ============================================================
-- VISA TYPE FAQS
-- The "Sıkça Sorulan Sorular" blocks on /vize-turleri and each
-- of its visa-type sub-pages. One row per question, grouped by
-- `page_key` (the sub-page slug, or 'vize-turleri' for the
-- main page). Managed from the admin panel under
-- "Vize Türleri" → the SSS field of each section.
--
-- Unlike country_faqs these are not tied to a country: the
-- content is generic guidance that applies to the visa type
-- regardless of destination.
-- ============================================================
CREATE TABLE IF NOT EXISTS visa_type_faqs (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  page_key    text NOT NULL,
  question    text NOT NULL,
  answer      text NOT NULL,
  sort_order  int  NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS visa_type_faqs_page_idx
  ON visa_type_faqs (page_key, sort_order);

ALTER TABLE visa_type_faqs ENABLE ROW LEVEL SECURITY;

-- Same policy shape as country_faqs: public read, admin write.
CREATE POLICY "public_select_visa_type_faqs"
  ON visa_type_faqs FOR SELECT USING (true);

CREATE POLICY "admin_insert_visa_type_faqs"
  ON visa_type_faqs FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM admin_profiles WHERE id = auth.uid()));

CREATE POLICY "admin_update_visa_type_faqs"
  ON visa_type_faqs FOR UPDATE
  USING (EXISTS (SELECT 1 FROM admin_profiles WHERE id = auth.uid()));

CREATE POLICY "admin_delete_visa_type_faqs"
  ON visa_type_faqs FOR DELETE
  USING (EXISTS (SELECT 1 FROM admin_profiles WHERE id = auth.uid()));


-- ============================================================
-- SEED
-- Idempotent: clears the seeded page keys first so re-running
-- the migration does not duplicate rows. Admin edits made after
-- the first run would be overwritten, so only run once.
-- ============================================================
DELETE FROM visa_type_faqs WHERE page_key IN (
  'vize-turleri',
  'turistik-vize',
  'ticari-vize',
  'aile-ziyareti-vizesi',
  'transit-vize',
  'fuar-kulturel-etkinlik-konferans-vizesi',
  'aile-birlesimi-vizesi',
  'ogrenci-vizesi',
  'calisma-vizesi'
);

INSERT INTO visa_type_faqs (page_key, question, answer, sort_order) VALUES

-- ---------- Ana sayfa: /vize-turleri ----------
('vize-turleri', 'Vize başvurusu için hangi belgeler gerekir?', $q$Gerekli belgeler; başvurulan ülkeye, vize türüne ve başvuru sahibinin kişisel durumuna göre değişir. Pasaport, başvuru formu, finansal durumu ve seyahat veya bulunma amacını destekleyen belgeler birçok başvuruda temel evraklar arasında yer alır. Başvuruya göre mesleki, eğitim, aile veya sponsorluk durumuna ilişkin ek belgeler de talep edilebilir.$q$, 0),
('vize-turleri', 'Vize başvurusu ne kadar sürede sonuçlanır?', $q$Başvurunun sonuçlanma süresi; vize türüne, başvurulan ülkeye, dönemsel yoğunluğa ve dosyanın incelenmesi için gereken ek işlemlere göre değişebilir. Bu nedenle başvurunun, planlanan seyahat veya eğitim başlangıcı gibi önemli tarihler dikkate alınarak yeterli süre önceden planlanması önemlidir.$q$, 1),
('vize-turleri', 'Vize başvurusu nereden yapılır?', $q$Başvurunun yapılacağı yer ve yöntem, ülkeye ve vize türüne göre değişir. Başvurular bazı durumlarda konsolosluk veya büyükelçilik üzerinden, bazı durumlarda ise yetkilendirilmiş başvuru merkezleri veya ilgili ülkenin çevrim içi başvuru sistemi üzerinden gerçekleştirilebilir.$q$, 2),
('vize-turleri', 'Vize başvurusu sırasında mülakat yapılır mı?', $q$Bazı vize türlerinde veya bazı ülkelerin uygulamalarında başvuru sahibinden mülakata katılması istenebilir. Mülakatın gerekip gerekmediği ve nasıl gerçekleştirileceği, başvurulan ülkeye ve vize kategorisine göre değişiklik gösterir.$q$, 3),
('vize-turleri', 'Vize başvurum reddedilirse tekrar başvurabilir miyim?', $q$Evet, birçok durumda ret kararının ardından yeniden başvuru yapılabilir. Ancak yeni başvuruda önceki ret gerekçelerinin dikkate alınması ve eksik veya sorunlu görülen noktaların mümkün olduğunca giderilmesi önemlidir.$q$, 4),
('vize-turleri', 'Vize başvurusu için randevu almak gerekir mi?', $q$Randevu gerekip gerekmediği, başvurulan ülkeye ve vize türüne göre değişir. Bazı başvurularda başvuru merkezinde veya konsoloslukta randevu alınması ve biyometrik işlemlerin tamamlanması gerekirken, bazı başvurular çevrim içi olarak yürütülebilir. Başvuru öncesinde ilgili ülkenin güncel başvuru prosedürünün kontrol edilmesi önemlidir.$q$, 5),
('vize-turleri', 'Vize başvurusunda önceki vizelerim veya retlerim önemli mi?', $q$Evet, önceki vize başvuruları ve seyahat geçmişi bazı başvurularda değerlendirmeye alınabilir. Daha önce alınmış vizeler, kullanılan vizeler, ülkeye giriş ve çıkışlar veya yaşanmış vize retleri başvuru dosyasının değerlendirilmesinde dikkate alınabilir. Önceki bir ret, tek başına yeni bir başvurunun reddedileceği anlamına gelmez; ancak önceki başvurudaki sorunların ve ret gerekçelerinin yeni dosyada dikkate alınması önemlidir.$q$, 6),
('vize-turleri', 'Vize başvurusunda verdiğim bilgiler daha sonra değişirse ne olur?', $q$Başvuru sonrasında seyahat tarihleri, konaklama, çalışma durumu, eğitim planı veya başvuruyu destekleyen diğer bilgiler değişebilir. Bu değişikliklerin vize sürecine etkisi, değişikliğin niteliğine ve başvurulan ülkenin uygulamalarına göre farklılık gösterebilir. Başvurunun amacı veya sunulan belgelerle ilgili önemli bir değişiklik olması halinde, ilgili makamın bilgilendirilmesi veya ek belge sunulması gerekebilir.$q$, 7),
('vize-turleri', 'Pasaportumun geçerlilik süresi vize başvurusunu etkiler mi?', $q$Evet. Birçok ülke, vize başvurusu veya ülkeye giriş sırasında pasaportun belirli bir süre daha geçerli olmasını şart koşar. Gerekli geçerlilik süresi ülkeye ve vize türüne göre değişebilir. Ayrıca pasaportta yeterli boş sayfa bulunması veya eski ve yeni pasaportlara ilişkin bilgilerin sunulması gibi ek şartlar da uygulanabilir. Bu nedenle başvuru öncesinde pasaportunuzun geçerlilik süresinin ilgili ülkenin güncel şartlarını karşıladığından emin olmanız gerekir.$q$, 8),
('vize-turleri', 'Vize başvurusunda davetiye almak vizeyi garanti eder mi?', $q$Hayır. Davetiye, seyahat amacını ve başvuru sahibinin karşı ülkedeki bağlantısını destekleyen önemli bir belge olabilir ancak tek başına vize verilmesini garanti etmez. Başvuru, davetiyenin yanı sıra başvuru sahibinin kişisel durumu, finansal yeterliliği, seyahat amacı ve sunduğu diğer belgelerle birlikte değerlendirilir. Davetiyenin resmi ve başvurunun gerçek amacıyla uyumlu olması da önemlidir.$q$, 9),

-- ---------- Turistik Vize ----------
('turistik-vize', 'Turistik vize başvurumu ne kadar önce yapmalıyım?', $q$Turistik vize başvurularının, seyahat tarihinden en az 1 ay önce planlanması tavsiye edilir. Ancak randevu yoğunlukları ve değerlendirme süreleri ülkeye göre değişebileceğinden, özellikle yoğun dönemlerde başvurunun daha erken yapılması faydalı olacaktır.$q$, 0),
('turistik-vize', 'Turistik vize kaç gün geçerlidir?', $q$Turistik vizeler her başvuruda aynı süreyle verilmez. Vizenin geçerlilik süresi ve ülkede kalınabilecek gün sayısı başvurunun değerlendirilmesine göre değişebilir. Ayrıca vizenin geçerlilik süresi ile izin verilen kalış süresi aynı değildir. Bu nedenle seyahat planı yapılırken vize üzerinde belirtilen süre ve koşullar dikkate alınmalıdır.$q$, 1),
('turistik-vize', 'Tek girişli ve çok girişli turistik vize arasındaki fark nedir?', $q$Tek girişli turistik vize, geçerlilik süresi içinde ülkeye veya ilgili vize bölgesine yalnızca bir kez giriş yapılmasına izin verir. Çok girişli (multiple entry) vize ise geçerlilik süresi boyunca, vize şartlarına uygun olmak kaydıyla birden fazla giriş ve çıkış yapma hakkı tanıyabilir.$q$, 2),
('turistik-vize', 'Turistik vize ile eğitim alabilir miyim?', $q$Bu durum başvurulan ülkenin uygulamalarına göre değişebilir. Bazı ülkeler kısa süreli kurs veya eğitim programlarına katılıma izin verebilirken, uzun süreli eğitimler için öğrenci vizesi veya farklı bir vize türüne başvurulması gerekir.$q$, 3),
('turistik-vize', 'Turistik vize başvurusu için uçak bileti satın almak zorunda mıyım?', $q$Birçok ülkede başvuru sırasında seyahat planını gösteren rezervasyon bilgileri talep edilse de, kesin satın alınmış uçak bileti zorunluluğu her zaman bulunmayabilir. Gereklilikler ülkeye göre değişebileceğinden, başvuru yapılacak ülkenin güncel uygulamalarının dikkate alınması önemlidir.$q$, 4),
('turistik-vize', 'Turistik vize ile ailemi veya arkadaşlarımı ziyaret edebilir miyim?', $q$Evet, birçok ülkede aile veya arkadaş ziyareti kısa süreli ziyaret amacı kapsamında değerlendirilebilir. Ancak bazı ülkeler, davetiye veya ziyaret amacını destekleyen ek belgeler talep edebilir. Başvuru şartları seyahat edeceğiniz ülkenin uygulamalarına göre değişiklik gösterebilir.$q$, 5),
('turistik-vize', 'Turistik vizeyle birden fazla ülkeye seyahat edebilir miyim?', $q$Bu durum, vizenin hangi ülke veya bölge için düzenlendiğine ve vizenin giriş koşullarına göre değişir. Bazı vizeler yalnızca belirli bir ülkeye giriş için geçerliyken, bazıları birden fazla ülkeye seyahat imkânı sağlayabilir. Seyahat planınızda birden fazla ülke bulunuyorsa, vizenin kapsamını ve giriş koşullarını başvuru öncesinde kontrol etmeniz gerekir.$q$, 6),
('turistik-vize', 'Vize aldıktan sonra seyahat tarihlerimi değiştirebilir miyim?', $q$Seyahat tarihlerinin değiştirilip değiştirilemeyeceği, vizenin geçerlilik süresine ve başvurulan ülkenin uygulamalarına göre değişebilir. Yeni seyahat tarihlerinin vizenin geçerlilik ve kullanım koşulları içinde olup olmadığı kontrol edilmelidir. Değişikliğin vizenin koşullarını karşılamadığı durumlarda yeni bir başvuru veya ek işlem gerekebilir.$q$, 7),

-- ---------- Ticari Vize ----------
('ticari-vize', 'Ticari vize başvurusu için şirketten izin veya görevlendirme yazısı gerekir mi?', $q$Başvuru sahibinin bir şirkette çalışan olarak ticari seyahat gerçekleştirmesi halinde, işveren tarafından düzenlenen görev veya izin yazısı talep edilebilir. Bu belgede seyahatin amacı, tarihleri, başvuru sahibinin şirketteki görevi ve seyahat masraflarının nasıl karşılanacağı gibi bilgilerin yer alması gerekebilir.$q$, 0),
('ticari-vize', 'Davet eden yabancı şirketin hangi belgelerini sunmam gerekir?', $q$Davet eden şirketin resmi davet yazısının yanı sıra, şirketin ticari faaliyetini ve yasal varlığını gösteren belgeler de talep edilebilir. Şirket kayıtları, ticari faaliyet belgeleri veya davet eden kurumun kimliğini doğrulayan belgeler başvurunun niteliğine göre dosyaya eklenebilir. Hangi belgelerin gerekli olduğu başvurulan ülkenin güncel belge listesine göre belirlenmelidir.$q$, 1),
('ticari-vize', 'Ticari vize başvurusu için karşı ülkeden davetiye şart mı?', $q$Her ticari vize başvurusunda davetiye zorunlu değildir. Davet mektubu, iş görüşmesi, toplantı, konferans veya benzeri ticari bir faaliyetin amacını destekleyen önemli bir belge olabilir; ancak bazı başvurularda ticari ilişkinin veya seyahat amacının başka belgelerle de ortaya konulması mümkündür. Bu nedenle davetiye gerekliliği başvurulan ülkenin ve planlanan faaliyetin koşullarına göre değerlendirilmelidir.$q$, 2),
('ticari-vize', 'İlk kez iş yapacağım yabancı şirketten aldığım davetiye yeterli olur mu?', $q$Tek başına davetiye, vize verilmesini garanti etmez. İlk kez kurulacak bir ticari ilişkinin söz konusu olduğu durumlarda, davet mektubunun yanı sıra görüşmenin veya iş ilişkisinin nedenini gösteren yazışmalar, teklif veya sipariş belgeleri, toplantı bilgileri ya da seyahatin ticari amacını destekleyen diğer belgeler talep edilebilir. Başvurunun bütün belgeleriyle birlikte tutarlı bir ticari amaç ortaya koyması önemlidir.$q$, 3),
('ticari-vize', 'Şirketim ile ziyaret edeceğim şirket arasındaki ticari ilişkiyi nasıl kanıtlayabilirim?', $q$Ticari ilişkinin niteliğine göre sözleşmeler, sipariş veya teklif belgeleri, proforma faturalar, önceki ticari yazışmalar, toplantı kayıtları veya taraflar arasındaki iş ilişkisini gösteren diğer belgeler kullanılabilir. Henüz kurulmuş bir ticari ilişki bulunmuyorsa, planlanan görüşmenin veya iş bağlantısının amacını açıklayan belgelerin sunulması önem kazanabilir.$q$, 4),
('ticari-vize', 'Şirket sahibiyim. Ticari vize başvurusunda durumumu nasıl belgelemeliyim?', $q$Şirket sahibi veya ortağı olan başvuru sahiplerinden, şirketle olan bağlarını ve ticari faaliyetlerini gösteren belgeler talep edilebilir. Şirket kayıtları, faaliyet veya kuruluş belgeleri, vergiye ilişkin belgeler ve başvuru sahibinin şirketteki konumunu gösteren resmi kayıtlar başvurunun niteliğine göre kullanılabilir. Sunulan belgelerin planlanan ticari seyahatle uyumlu olması önemlidir.$q$, 5),
('ticari-vize', 'Fuara ziyaretçi olarak katılmak ile stant açarak katılmak vize başvurusunu etkiler mi?', $q$Evet. Seyahatin amacı ve fuardaki rolünüz, başvuruda sunulması gereken belgeleri etkileyebilir. Ziyaretçi olarak katılımda fuar kaydı veya giriş bileti seyahat amacını destekleyebilirken, stant sahibi veya katılımcı olarak gidilmesi halinde stant sözleşmesi, organizasyon belgeleri veya katılımcı kaydını gösteren ek belgeler gerekebilir.$q$, 6),
('ticari-vize', 'Ticari seyahat masraflarını kim karşılayabilir ve bu durum nasıl belgelenir?', $q$Seyahat masrafları başvuru sahibi, çalıştığı şirket veya bazı durumlarda davet eden kurum tarafından karşılanabilir. Masrafları kimin üstlendiği başvuru formu ve destekleyici belgelerde açıkça belirtilmeli ve mümkün olduğunca resmi belgelerle desteklenmelidir. Finansal yeterlilik değerlendirmesi, başvurulan ülkenin uygulamalarına göre ayrıca yapılabilir.$q$, 7),
('ticari-vize', 'Birden fazla şirket veya iş görüşmesini aynı seyahat kapsamında gösterebilir miyim?', $q$Evet, seyahat planınızda birden fazla şirket ziyareti veya iş görüşmesi bulunabilir. Bu durumda seyahat programının tüm görüşmeleri ve ziyaretleri açıkça göstermesi ve mümkünse her ticari faaliyetin ilgili davet, toplantı veya ilişki belgeleriyle desteklenmesi gerekir. Başvurudaki seyahat planının tutarlı ve gerçekçi olması önemlidir.$q$, 8),
('ticari-vize', 'Ticari vize ile hangi faaliyetleri yapabilirim?', $q$Ticari vizenin izin verdiği faaliyetler başvurulan ülkenin mevzuatına ve verilen vizenin koşullarına göre değişir. Ticari vize genel olarak iş görüşmeleri, toplantılar, şirket ziyaretleri, fuar ve konferans gibi kısa süreli ticari faaliyetler için kullanılır. Ancak vizenin çalışma veya ülkede ücretli istihdam hakkı verip vermediği ayrıca değerlendirilmelidir; ticari faaliyet ile çalışma arasındaki ayrım ülkeye göre farklı kurallara tabi olabilir.$q$, 9),

-- ---------- Aile Ziyareti Vizesi ----------
('aile-ziyareti-vizesi', 'Aile ziyareti vizesi için davetiye almak zorunlu mu?', $q$Davetiye gerekip gerekmediği, başvurulan ülkenin uygulamalarına ve ziyaretin niteliğine göre değişebilir. Davetiye, ziyaret edilecek kişinin başvuru sahibini kabul ettiğini ve seyahatin amacını desteklediğini gösterebilir; ancak bazı başvurularda ziyaretin amacı ve aile ilişkisi başka belgelerle de desteklenebilir.$q$, 0),
('aile-ziyareti-vizesi', 'Davetiye gönderen kişinin hangi belgeleri sunması gerekir?', $q$Davetiye gönderen kişinin kimliği, ülkedeki yasal statüsü, adresi ve başvuru sahibiyle olan ilişkisini gösteren belgeler talep edilebilir. Bazı ülkelerde davet eden kişinin konaklama veya seyahat masraflarını üstlenmesi halinde bunu gösteren ek belgeler de istenebilir.$q$, 1),
('aile-ziyareti-vizesi', 'Aile bağımı nasıl kanıtlayabilirim?', $q$Aile ilişkisine göre doğum kayıtları, evlilik belgeleri, nüfus kayıtları veya ilgili resmi kayıtlar kullanılabilir. Hangi belgenin kabul edileceği, başvurulan ülkeye ve kurulan aile ilişkisinin niteliğine göre değişebilir.$q$, 2),
('aile-ziyareti-vizesi', 'Davet eden kişi masraflarımı karşılayabilir mi?', $q$Bazı ülkelerde davet eden kişi, ziyaret sırasında konaklama veya diğer seyahat masraflarını kısmen ya da tamamen üstlenebilir. Bu durumda davet eden kişinin finansal durumunu ve masrafları karşılayacağını gösteren belgeler talep edilebilir. Bununla birlikte başvuru sahibinin kendi finansal durumu da başvurunun koşullarına göre değerlendirmeye alınabilir.$q$, 3),
('aile-ziyareti-vizesi', 'Davet eden kişinin evinde kalacaksam otel rezervasyonu yapmam gerekir mi?', $q$Her başvuruda otel rezervasyonu zorunlu değildir. Davet eden kişinin evinde konaklanacaksa, bu durumun davet mektubu ve gerekli konaklama belgeleriyle gösterilmesi yeterli olabilir. Hangi belgelerin kabul edileceği başvurulan ülkenin güncel uygulamalarına göre değişir.$q$, 4),
('aile-ziyareti-vizesi', 'Aile ziyareti vizesi ile birden fazla aile bireyimi ziyaret edebilir miyim?', $q$Bu durum vizenin koşullarına ve seyahat planına göre değişebilir. Aynı seyahat kapsamında birden fazla aile bireyinin ziyaret edilmesi planlanıyorsa, ziyaret edilecek kişilerin ve konaklama düzenlemelerinin başvuru sırasında açıkça belirtilmesi ve mümkün olduğunca belgelerle desteklenmesi gerekir.$q$, 5),
('aile-ziyareti-vizesi', 'Aile ziyareti vizesi ile ne kadar süre kalabilirim?', $q$İzin verilen kalış süresi, vizenin koşullarına ve başvurulan ülkenin uygulamalarına göre değişebilir. Vizenin geçerlilik süresi ile ülkede kalabileceğiniz süre aynı olmayabileceğinden, seyahat öncesinde vize üzerindeki giriş ve kalış koşullarının kontrol edilmesi gerekir.$q$, 6),
('aile-ziyareti-vizesi', 'Aile ziyareti vizesi ile ailemin yanında çalışabilir miyim?', $q$Aile ziyareti vizesi, kural olarak kısa süreli ziyaret amacıyla verilir ve çalışma hakkı sağlamaz. Ziyaret sırasında çalışmayı planlayan kişilerin, ilgili ülkenin bu faaliyet için öngördüğü izin veya vize koşullarını ayrıca karşılaması gerekir.$q$, 7),
('aile-ziyareti-vizesi', 'Aile ziyareti vizesi başvurusunda önceki vizelerim veya retlerim dikkate alınır mı?', $q$Önceki vize başvuruları ve seyahat geçmişi, başvurulan ülkenin uygulamalarına göre değerlendirmeye alınabilir. Daha önce alınmış vizeler, seyahat geçmişi veya yaşanmış retler başvurunun incelenmesinde dikkate alınabilir. Önceki bir ret tek başına yeni bir başvurunun reddedileceği anlamına gelmez; ancak önceki başvurudaki sorunların yeni dosyada dikkate alınması önemlidir.$q$, 8),
('aile-ziyareti-vizesi', 'Aile ziyareti vizesi başvurum reddedilirse tekrar başvurabilir miyim?', $q$Birçok durumda ret kararından sonra yeniden başvuru yapılabilir. Ancak yeni başvuruda önceki ret gerekçelerinin incelenmesi ve dosyada sorun oluşturan noktaların mümkün olduğunca giderilmesi önemlidir.$q$, 9),

-- ---------- Transit Vize ----------
('transit-vize', 'Aktarma yapacağım ülkede transit vize almam gerekir mi?', $q$Transit vize gerekip gerekmediği; aktarma yapılan ülkeye, yolcunun vatandaşlığına, seyahat güzergâhına ve aktarma sırasında uluslararası transit alanından çıkılıp çıkılmadığına göre değişir. Bazı ülke vatandaşları için yalnızca havalimanının uluslararası transit alanından geçişte dahi transit vizesi gerekebilir. Bu nedenle yalnızca aktarma yapılıyor olması vize gerekip gerekmediğini tek başına belirlemez.$q$, 0),
('transit-vize', 'Havalimanından çıkmadan aktarma yapıyorsam transit vize gerekir mi?', $q$Her zaman değil. Uluslararası transit alanından ayrılmadan yapılan aktarmalarda bazı yolcular transit vizeden muaf olabilirken, bazı ülke vatandaşları için bu alandan çıkılmasa dahi havalimanı transit vizesi zorunlu olabilir. Gereklilik, vatandaşlık ve aktarma yapılan ülkenin kurallarına göre kontrol edilmelidir.$q$, 1),
('transit-vize', 'Transit vize ile havalimanından çıkabilir miyim?', $q$Havalimanı transit vizesi, uluslararası transit alanından geçiş ve bağlantılı uçuşu bekleme amacıyla verilir; Schengen bölgesine giriş hakkı sağlamaz. Havalimanından çıkmak veya Schengen bölgesine giriş yapmak için, koşullara göre kısa süreli Schengen vizesi veya başka bir giriş izni gerekebilir.$q$, 2),
('transit-vize', 'Transit vize ile Schengen ülkesine giriş yapabilir miyim?', $q$Hayır, havalimanı transit vizesi tek başına Schengen bölgesine giriş hakkı vermez. Uluslararası transit alanından ayrılarak Schengen ülkesine giriş yapılması gereken durumlarda, yolcunun vatandaşlığına ve seyahat koşullarına göre ayrıca giriş vizesi gerekebilir.$q$, 3),
('transit-vize', 'Schengen ülkesinde iki farklı havalimanında aktarma yapacaksam transit vize yeterli olur mu?', $q$Genellikle hayır. Bir Schengen ülkesine başka bir Schengen ülkesindeki havalimanı üzerinden ulaşmak veya Schengen bölgesi dışındaki bir ülkeye iki farklı Schengen havalimanından geçerek seyahat etmek, yalnızca havalimanı transit geçişi olarak değerlendirilmez. Böyle bir güzergâhta Schengen bölgesine giriş söz konusu olabileceğinden, yolcunun kısa süreli vize gerekliliği ayrıca değerlendirilmelidir.$q$, 4),
('transit-vize', 'Transit vize için hangi belgeler gerekir?', $q$Gerekli belgeler başvurulan ülkeye ve seyahat güzergâhına göre değişebilir. Genellikle geçerli pasaport, uçuş veya ulaşım bilgileri, nihai varış ülkesine ilişkin vize veya giriş izni ve seyahat güzergâhını gösteren belgeler talep edilebilir. Başvuru sahibinin durumuna göre ek belgeler de istenebilir.$q$, 5),
('transit-vize', 'Transit vize başvurusunda nihai varış ülkesinin vizesi gerekli midir?', $q$Bazı durumlarda evet. Transit geçişin amacı, başka bir ülkeye devam etmek olduğundan, nihai varış ülkesine giriş yapabilme hakkını gösteren vize veya diğer belgeler başvurunun değerlendirilmesinde önem taşıyabilir. Gerekli belgenin niteliği nihai varış ülkesinin kurallarına ve seyahat güzergâhına göre değişir.$q$, 6),
('transit-vize', 'Transit vize ile ne kadar süre kalabilirim?', $q$Havalimanı transit vizesi, ülkede konaklama veya normal ziyaret amacıyla verilen bir vize değildir. Uluslararası transit alanından bağlantılı uçuşa geçiş amacıyla kullanılır ve vizenin koşulları verilen transit hakkıyla sınırlıdır. Bu nedenle transit vizenin geçerlilik süresi ile ülkede kalma hakkı birbirine karıştırılmamalıdır.$q$, 7),
('transit-vize', 'Uçuşumun aktarma süresi uzarsa transit vizem geçerli olur mu?', $q$Transit vizenin geçerliliği ve kullanılabileceği koşullar, verilen vizenin türüne ve üzerindeki bilgilere göre değerlendirilir. Uçuş değişikliği, aktarma noktasının değişmesi veya planlanan güzergâhın farklılaşması vizenin kullanım koşullarını etkileyebilir. Bu nedenle seyahat öncesinde yeni güzergâhın mevcut vizeyle uyumlu olup olmadığı kontrol edilmelidir.$q$, 8),
('transit-vize', 'Transit vize başvurum reddedilirse tekrar başvurabilir miyim?', $q$Birçok durumda ret kararından sonra yeniden başvuru yapılabilir. Ancak yeni başvuruda önceki ret gerekçelerinin dikkate alınması ve transit geçişin gerekliliğini veya koşullarını etkileyen sorunların mümkün olduğunca giderilmesi önemlidir.$q$, 9),

-- ---------- Fuar, Kültürel Etkinlik ve Konferans Vizesi ----------
('fuar-kulturel-etkinlik-konferans-vizesi', 'Fuara katılmak için hangi vize türüne başvurmalıyım?', $q$Fuarın amacı, fuara katılım şekliniz ve seyahat sırasında gerçekleştireceğiniz faaliyetlere göre başvuru kategorisi değişebilir. Sadece ziyaretçi olarak fuara katılmak ile stant açmak, şirket adına temsil yapmak veya ticari görüşmeler yürütmek aynı şekilde değerlendirilmeyebilir. Bu nedenle başvuru kategorisinin fuardaki gerçek faaliyetinizle uyumlu olması önemlidir.$q$, 0),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Fuara sadece ziyaretçi olarak katılacaksam hangi belgeleri sunmalıyım?', $q$Fuar giriş bileti, kayıt belgesi veya organizatörden alınan katılım belgesi seyahat amacını destekleyen belgeler arasında yer alabilir. Başvuru sahibinin seyahat planına göre konaklama, ulaşım, finansal durum ve mesleki durumunu gösteren ek belgeler de talep edilebilir.$q$, 1),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Fuarda stant açacaksam başvurum farklı değerlendirilir mi?', $q$Evet. Stant sahibi veya katılımcı olarak fuara gitmek, yalnızca ziyaretçi olarak katılmaktan farklı bir faaliyet niteliği taşıyabilir. Bu durumda stant kiralama sözleşmesi, katılımcı kaydı, organizatörle yapılan sözleşme veya ödeme belgeleri gibi ek evraklar gerekebilir. Başvuruda fuardaki gerçek rolünüzün açıkça gösterilmesi önemlidir.$q$, 2),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Konferansa katılmak için davetiye şart mı?', $q$Her başvuruda aynı belge zorunlu olmayabilir. Konferans kayıt belgesi, davet yazısı, giriş bileti veya organizatör tarafından düzenlenen katılım belgesi seyahat amacını destekleyebilir. Hangi belgenin kabul edileceği başvurulan ülkenin uygulamalarına ve etkinliğin niteliğine göre değişebilir.$q$, 3),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Etkinliğe kayıt oldum ancak organizatörden davetiye almadım. Vize başvurusu yapabilir miyim?', $q$Bazı durumlarda evet. Etkinlik kaydı, giriş bileti veya organizatör tarafından verilen katılım belgesi seyahat amacını destekleyebilir. Ancak davetiye veya başka bir etkinlik belgesinin zorunlu olup olmadığı başvurulan ülkenin güncel şartlarına göre kontrol edilmelidir.$q$, 4),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Kültürel bir etkinliğe katılmak için vize alabilir miyim?', $q$Evet. Kısa süreli kültürel etkinlikler, festivaller, sergiler, gösteriler veya benzeri organizasyonlara katılım bazı ülkelerin kısa süreli vize kategorileri kapsamında değerlendirilebilir. Etkinliğin niteliğini ve katılım amacını gösteren belgelerin başvuru dosyasına eklenmesi gerekir.$q$, 5),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Konferansa konuşmacı olarak katılmak ile dinleyici olarak katılmak arasında fark var mı?', $q$Olabilir. Konuşmacı, panelist veya organizasyonun aktif katılımcısı olarak seyahat eden kişinin etkinlikle ilişkisini gösteren davet, konuşmacı kaydı veya organizatör yazısı gibi ek belgeler gerekebilir. Sadece dinleyici olarak katılan kişiler için ise kayıt veya giriş belgesi yeterli olabilir. Gereklilikler etkinliğin ve başvurulan ülkenin uygulamalarına göre değişir.$q$, 6),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Etkinliğin masraflarını organizatör karşılıyorsa bunu nasıl göstermeliyim?', $q$Seyahat, konaklama veya diğer masrafların organizatör tarafından karşılanması halinde bu durum davet yazısı, sponsorluk yazısı veya organizatörün sunduğu diğer belgelerle gösterilebilir. Başvuru dosyasındaki masraf bilgileri ile diğer belgelerin birbiriyle uyumlu olması önemlidir.$q$, 7),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Etkinlik için aldığım vizeyle etkinlik dışında turistik gezi yapabilir miyim?', $q$Bu durum vizenin türüne, geçerlilik süresine ve başvurulan ülkenin kurallarına göre değişebilir. Etkinlik, seyahatin temel amacı olarak başvuruda doğru şekilde belirtilmelidir. Vize koşullarının izin verdiği ölçüde kısa süreli kişisel faaliyetler mümkün olabilir; ancak vize, başvuruda beyan edilmeyen farklı bir ana amaç için kullanılmamalıdır.$q$, 8),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Etkinlik tarihi değişirse veya etkinlik iptal edilirse vizem geçerli olur mu?', $q$Etkinlik tarihinin değişmesi veya iptal edilmesi, vizenin kullanım koşullarını etkileyebilir. Özellikle vize belirli bir etkinlik veya seyahat planına dayanarak verilmişse, değişikliğin vizenin şartlarıyla uyumlu olup olmadığı kontrol edilmelidir. Gerekli durumlarda ilgili makamdan bilgi alınması veya yeni bir başvuru yapılması gerekebilir.$q$, 9),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Aynı seyahatte birden fazla etkinliğe katılabilir miyim?', $q$Bu durum vizenin geçerlilik süresine, giriş hakkına ve seyahat planına bağlıdır. Birden fazla etkinlik planlanıyorsa tüm etkinliklerin ve seyahat güzergâhının başvuru sırasında mümkün olduğunca açık şekilde belirtilmesi, sunulan belgelerin de bu planı desteklemesi önemlidir.$q$, 10),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Etkinlik vizesiyle çalışabilir miyim?', $q$Kural olarak hayır. Etkinlik amacıyla verilen kısa süreli vize, otomatik olarak çalışma hakkı sağlamaz. Etkinlik kapsamında gerçekleştirilecek faaliyet ücretli çalışma veya ilgili ülkede profesyonel faaliyet yürütme niteliğindeyse, ayrıca çalışma izni veya farklı bir vize türü gerekebilir.$q$, 11),
('fuar-kulturel-etkinlik-konferans-vizesi', 'Vize başvurum etkinlik tarihine yetişmezse ne yapmalıyım?', $q$Başvuruların sonuçlanma süresi ülkeye, başvuru türüne ve dönemsel yoğunluğa göre değişebilir. Etkinlik tarihi kesin olan başvuruların mümkün olduğunca erken planlanması önemlidir. Başvuru yapılmadan önce randevu ve işlem sürelerinin kontrol edilmesi, etkinlik tarihine yeterli zaman bırakılması açısından faydalıdır.$q$, 12),

-- ---------- Aile Birleşimi Vizesi ----------
('aile-birlesimi-vizesi', 'Aile birleşimi vizesine kimler başvurabilir?', $q$Aile birleşimi vizesine kimlerin başvurabileceği, başvurulan ülkenin mevzuatına ve ülkede yaşayan aile bireyiyle olan hukuki ilişkiye göre değişir. Eşler ve çocuklar birçok ülkede temel aile birleşimi kategorileri arasında yer alırken, bazı ülkelerde diğer aile bireyleri için de belirli şartlarla başvuru yapılabilir.$q$, 0),
('aile-birlesimi-vizesi', 'Eşim yurt dışında yaşıyorsa aile birleşimi vizesine başvurabilir miyim?', $q$Eşinizin yaşadığı ülkedeki vatandaşlık veya oturum statüsü ile aile birleşimi için aranan diğer şartları karşılamanız halinde başvuru mümkün olabilir. Eşin statüsü, gelir durumu, konut koşulları ve aile birleşimine ilişkin diğer yasal şartlar ülkeye göre değişebilir.$q$, 1),
('aile-birlesimi-vizesi', 'Aile birleşimi vizesi için evlilik şart mı?', $q$Her durumda aynı şart uygulanmaz. Eş üzerinden yapılan aile birleşimi başvurularında evliliğin hukuken geçerli olması gerekirken, bazı ülkeler belirli şartlarla kayıtlı partnerlik veya benzeri ilişkileri de kabul edebilir. Hangi ilişkilerin aile birleşimi kapsamında değerlendirileceği ülkenin mevzuatına göre belirlenir.$q$, 2),
('aile-birlesimi-vizesi', 'Aile birleşimi için evliliğin belirli bir süre devam etmiş olması gerekir mi?', $q$Bu şart ülkeye ve başvurunun dayandığı hukuki kategoriye göre değişebilir. Bazı ülkelerde evliliğin süresinden ziyade gerçek ve geçerli bir aile ilişkisinin bulunması esas alınırken, bazı özel durumlarda farklı şartlar uygulanabilir.$q$, 3),
('aile-birlesimi-vizesi', 'Aile birleşimi vizesi için dil sınavı veya dil belgesi gerekir mi?', $q$Bazı ülkeler aile birleşimi başvurularında başvuru sahibinden belirli düzeyde dil bilgisi göstermesini isteyebilir. Ancak dil şartının bulunup bulunmadığı, gerekli dil seviyesinin ne olduğu ve muafiyetlerin kapsamı ülkeye ve başvuru sahibinin durumuna göre değişir.$q$, 4),
('aile-birlesimi-vizesi', 'Aile birleşimi vizesinde gelir şartı var mı?', $q$Bazı ülkeler, ülkede yaşayan aile bireyinin aile birleşimi sonrasında ailenin geçimini sağlayabilecek yeterli ve düzenli gelire sahip olmasını şart koşabilir. Gelir şartının uygulanıp uygulanmadığı ve gerekli gelir düzeyi ülkeye, aile büyüklüğüne ve başvuru kategorisine göre değişebilir.$q$, 5),
('aile-birlesimi-vizesi', 'Aile birleşimi için ev şartı var mı?', $q$Bazı ülkelerde aile birleşimi başvurusunda aile bireylerinin yaşayacağı konutun belirli şartları karşılaması gerekir. Konutun büyüklüğü, uygunluğu ve aile bireylerinin birlikte yaşayacağı koşullar ülkenin mevzuatına göre değerlendirilebilir.$q$, 6),
('aile-birlesimi-vizesi', 'Çocuğumu aile birleşimi kapsamında yanıma alabilir miyim?', $q$Çocukların aile birleşimi kapsamında başvuru yapıp yapamayacağı; çocuğun yaşı, aile bireylerinin hukuki durumu, velayet ilişkisi ve başvurulan ülkenin mevzuatına göre değişebilir. Özellikle diğer ebeveynin velayet veya izin durumu bazı başvurularda ayrıca belgelenebilir.$q$, 7),
('aile-birlesimi-vizesi', 'Aile birleşimi başvurusunda mülakat yapılır mı?', $q$Bazı ülkelerde veya başvuru kategorilerinde mülakat yapılabilir. Mülakatın amacı ve uygulanma şekli ülkeye göre değişmekle birlikte, aile ilişkisi, başvuru amacı veya başvuruda sunulan bilgiler hakkında ek değerlendirme yapılması söz konusu olabilir.$q$, 8),
('aile-birlesimi-vizesi', 'Aile birleşimi başvurusunda evliliğin gerçek olduğu nasıl kanıtlanır?', $q$Başvuruda öncelikle resmi evlilik ve aile bağını gösteren belgeler sunulur. Bazı durumlarda başvuru makamları ilişkinin gerçekliğini değerlendirmek için ek belgeler veya açıklamalar talep edebilir. Sunulan bilgilerin ve belgelerin birbiriyle tutarlı olması önemlidir.$q$, 9),
('aile-birlesimi-vizesi', 'Aile birleşimi vizesi ne kadar sürede sonuçlanır?', $q$Sonuçlanma süresi başvurulan ülkeye, başvuru kategorisine, dosyanın incelenme sürecine ve ilgili göç veya vize makamlarının işlem yoğunluğuna göre değişebilir. Bazı aile birleşimi başvurularında vize kararı öncesinde yurt dışındaki göç makamlarının ayrıca değerlendirme yapması süreci uzatabilir.$q$, 10),
('aile-birlesimi-vizesi', 'Aile birleşimi başvurum reddedilirse tekrar başvurabilir miyim?', $q$Ret kararının ardından yeniden başvuru yapılabilmesi, ret gerekçesine ve başvurulan ülkenin prosedürlerine göre değişebilir. Bazı durumlarda itiraz hakkı bulunurken, bazı durumlarda eksiklikler giderilerek yeni bir başvuru yapılabilir. Yeni bir başvuru yapılacaksa önceki ret gerekçelerinin dikkatle değerlendirilmesi önemlidir.$q$, 11),
('aile-birlesimi-vizesi', 'Aile birleşimi vizesi ile çalışabilir miyim?', $q$Bu konu, başvurulan ülkenin oturum ve çalışma mevzuatına göre değişir. Bazı ülkelerde aile birleşimi kapsamında verilen oturum izni çalışma hakkı sağlayabilirken, bazı durumlarda ayrıca çalışma izni veya başka bir işlem gerekebilir. Bu nedenle vizenin veya oturum izninin çalışma hakkı verip vermediği ayrıca kontrol edilmelidir.$q$, 12),
('aile-birlesimi-vizesi', 'Aile birleşimi vizesi ile ülkede ne kadar süre kalabilirim?', $q$Aile birleşimi, kısa süreli ziyaret amacıyla verilen vizelerden farklı olarak uzun süreli yerleşim amacı taşır. Ülkede kalış süresi ve sonrasında verilecek oturum izninin süresi, başvurulan ülkenin mevzuatına ve verilen oturum statüsüne göre belirlenir.$q$, 13),
('aile-birlesimi-vizesi', 'Aile birleşimi başvurusu ile turist vizesi arasındaki fark nedir?', $q$Turistik vize geçici bir ziyaret amacı taşırken, aile birleşimi başvurusu aile bireyinin yanına uzun süreli olarak yerleşme amacıyla yapılır. Bu nedenle aile birleşimi başvurularında aile ilişkisi, ülkede yaşayan aile bireyinin statüsü ve uzun süreli yerleşim şartları ayrıca değerlendirilir.$q$, 14),

-- ---------- Öğrenci Vizesi ----------
('ogrenci-vizesi', 'Öğrenci vizesi için okuldan kabul almak zorunda mıyım?', $q$Çoğu öğrenci vizesi başvurusunda eğitim kurumundan resmi kabul veya kayıt belgesi temel belgeler arasında yer alır. Kabul belgesinin niteliği ve kabul edilmesi gereken kurumların şartları ülkeye ve eğitim programına göre değişebilir.$q$, 0),
('ogrenci-vizesi', 'Dil okuluna gitmek için öğrenci vizesi alabilir miyim?', $q$Bazı ülkelerde uzun süreli dil eğitimi için öğrenci vizesi veya eğitim amacıyla verilen başka bir uzun süreli vize kategorisi kullanılabilir. Gerekli vize türü eğitim programının süresine, niteliğine ve ülkenin mevzuatına göre belirlenir.$q$, 1),
('ogrenci-vizesi', 'Üniversite, yüksek lisans ve doktora için aynı öğrenci vizesi mi kullanılır?', $q$Bu durum ülkeye göre değişebilir. Bazı ülkelerde farklı eğitim seviyeleri aynı öğrenci vizesi kategorisi kapsamında değerlendirilirken, bazı ülkelerde programın niteliğine veya süresine göre farklı başvuru prosedürleri uygulanabilir.$q$, 2),
('ogrenci-vizesi', 'Öğrenci vizesi için ne kadar para göstermem gerekir?', $q$Gerekli finansal yeterlilik miktarı ülkeye, eğitim süresine, eğitim ücretlerine ve öğrencinin yaşam giderlerine göre değişebilir. Bazı ülkeler belirli bir aylık veya yıllık yaşam giderinin karşılanabileceğinin gösterilmesini isterken, bazıları eğitim ücreti ve konaklama gibi giderleri ayrıca değerlendirebilir.$q$, 3),
('ogrenci-vizesi', 'Öğrenci vizesi için ailem sponsor olabilir mi?', $q$Birçok ülkede öğrencinin eğitim ve yaşam giderlerinin ailesi veya başka bir sponsor tarafından karşılanması mümkün olabilir. Bu durumda sponsorun öğrenciyle olan ilişkisini ve masrafları karşılayabilecek mali yeterliliğini gösteren belgeler talep edilebilir.$q$, 4),
('ogrenci-vizesi', 'Öğrenci vizesi için banka hesabında para ne kadar süre bulunmalı?', $q$Bu konuda tek bir süre veya kural yoktur. Banka bakiyesinin ne şekilde ve ne kadar süreyle gösterilmesi gerektiği başvurulan ülkenin güncel şartlarına göre değişebilir. Bazı ülkeler belirli dönemlere ait banka hesap dökümlerini veya finansal geçmişi gösteren belgeleri talep edebilir.$q$, 5),
('ogrenci-vizesi', 'Öğrenci vizesi için konaklama göstermek zorunda mıyım?', $q$Bazı ülkeler öğrencinin eğitim süresince nerede kalacağını gösteren belge talep edebilir. Yurt kaydı, kira sözleşmesi, üniversite konaklama belgesi veya uygun başka bir konaklama kanıtı kabul edilebilir. Gerekli belgenin türü ülkeye göre değişir.$q$, 6),
('ogrenci-vizesi', 'Öğrenci vizesi ile çalışabilir miyim?', $q$Bazı ülkeler öğrencilere eğitimleri sırasında belirli koşullar ve süre sınırları dahilinde çalışma hakkı tanırken, bazı ülkelerde çalışma için ayrıca izin gerekebilir. Çalışma hakkının kapsamı eğitim seviyesine, vize veya oturum statüsüne ve ülkenin güncel mevzuatına göre değişir.$q$, 7),
('ogrenci-vizesi', 'Öğrenci vizesi ile eğitim süremden daha uzun kalabilir miyim?', $q$Öğrenci vizesinin veya buna bağlı oturum izninin geçerlilik süresi, eğitim programının süresine ve ülkenin uygulamalarına göre belirlenir. Eğitimin uzaması halinde vize veya oturum statüsünün uzatılması gerekebilir.$q$, 8),
('ogrenci-vizesi', 'Eğitim programım başlamadan önce ülkeye gidebilir miyim?', $q$Ülkeye giriş tarihi, verilen vizenin geçerlilik başlangıç tarihine ve ülkenin giriş kurallarına bağlıdır. Vize alınmış olması, vize üzerinde belirtilen geçerlilik tarihinden önce ülkeye giriş yapılabileceği anlamına gelmez.$q$, 9),
('ogrenci-vizesi', 'Öğrenci vizesi için mülakat yapılır mı?', $q$Bazı ülkeler veya başvuru kategorileri öğrenci vizesi sürecinde mülakat uygulayabilir. Mülakatta eğitim programı, okul seçimi, finansal kaynaklar ve eğitim planı hakkında sorular yöneltilebilir. Mülakatın yapılıp yapılmayacağı ülkeye ve başvuru kategorisine göre değişir.$q$, 10),
('ogrenci-vizesi', 'Öğrenci vizesi başvurum reddedilirse tekrar başvurabilir miyim?', $q$Ret kararından sonra yeniden başvuru yapılması veya bazı ülkelerde karara itiraz edilmesi mümkün olabilir. Yeni başvuru yapılacaksa önceki ret gerekçelerinin dikkatle incelenmesi ve sorun oluşturan noktaların giderilmesi önemlidir.$q$, 11),
('ogrenci-vizesi', 'Öğrenci vizesiyle başka ülkelere seyahat edebilir miyim?', $q$Bu durum öğrenci vizesinin hangi ülke tarafından verildiğine, vizenin niteliğine ve seyahat edilecek ülkenin giriş kurallarına göre değişir. Bir ülkenin öğrenci vizesi, başka ülkelere otomatik olarak giriş hakkı sağlamaz. Seyahat planı yapılmadan önce gidilecek ülkenin ayrıca vize veya giriş şartları kontrol edilmelidir.$q$, 12),
('ogrenci-vizesi', 'Öğrenci vizesi ile mezun olduktan sonra ülkede kalabilir miyim?', $q$Bazı ülkeler mezun olan öğrenciler için eğitim sonrasında belirli süreyle ülkede kalma, iş arama veya çalışma imkânı sağlayan ayrı oturum veya izin türleri sunabilir. Bu hak otomatik olarak öğrenci vizesinin devamı anlamına gelmez ve ülkenin güncel göç mevzuatına göre ayrıca değerlendirilir.$q$, 13),

-- ---------- Çalışma Vizesi ----------
('calisma-vizesi', 'Çalışma vizesi almak için iş teklifi almak zorunda mıyım?', $q$Birçok çalışma vizesi kategorisinde başvuru öncesinde bir işveren tarafından sunulmuş iş teklifi veya imzalanmış iş sözleşmesi gerekir. Ancak bazı ülkelerde belirli meslek grupları veya nitelikli çalışanlar için iş teklifinden farklı başvuru yolları bulunabilir. Hangi şartın geçerli olduğu başvurulan ülkeye ve çalışma kategorisine göre değişir.$q$, 0),
('calisma-vizesi', 'İşverenim benim için çalışma izni almak zorunda mı?', $q$Bazı ülkelerde çalışma izni veya işveren tarafından yapılması gereken resmi bir başvuru bulunurken, bazı sistemlerde çalışma hakkı doğrudan vize veya oturum izni kapsamında düzenlenebilir. İşverenin hangi işlemleri yapması gerektiği ülkeye ve çalışma kategorisine göre değişir.$q$, 1),
('calisma-vizesi', 'Çalışma vizesi için diploma veya mesleki yeterlilik belgesi gerekir mi?', $q$Bu durum yapılacak işe ve başvurulan ülkenin şartlarına göre değişir. Bazı mesleklerde diploma, mesleki yeterlilik, lisans veya denklik belgesi zorunlu olabilirken, bazı işlerde mesleki deneyim daha önemli bir kriter olabilir.$q$, 2),
('calisma-vizesi', 'Çalışma vizesi için dil bilmek zorunda mıyım?', $q$Her çalışma vizesinde aynı dil şartı uygulanmaz. Bazı ülkeler veya meslek grupları belirli düzeyde dil yeterliliği ararken, bazı çalışma kategorilerinde böyle bir şart bulunmayabilir. Dil şartının olup olmadığı ve gerekli seviyenin ne olduğu başvurulan ülkeye ve mesleğe göre değerlendirilmelidir.$q$, 3),
('calisma-vizesi', 'Çalışma vizesi için maaş şartı var mı?', $q$Bazı ülkeler yabancı çalışanların belirli bir asgari maaş veya mesleğe göre belirlenen ücret seviyesini karşılamasını şart koşabilir. Bu eşik; mesleğe, çalışma kategorisine, yaşa veya başka koşullara göre farklılaşabilir. İş sözleşmesindeki ücretin ilgili ülkenin güncel şartlarını karşılayıp karşılamadığı kontrol edilmelidir.$q$, 4),
('calisma-vizesi', 'Çalışma vizesi ile istediğim işte çalışabilir miyim?', $q$Her zaman değil. Çalışma hakkı belirli bir işverene, mesleğe, sektöre veya çalışma izninin koşullarına bağlı olabilir. Vizenin veya çalışma izninin hangi iş ve işveren için geçerli olduğu kontrol edilmeden farklı bir işte çalışmaya başlanmamalıdır.$q$, 5),
('calisma-vizesi', 'Çalışma vizesi aldıktan sonra işverenimi değiştirebilir miyim?', $q$Bu durum çalışma izninin niteliğine ve başvurulan ülkenin mevzuatına göre değişir. Bazı izinler belirli bir işverene bağlıyken, bazı oturum veya çalışma izinleri daha geniş çalışma hakkı sağlayabilir. İşveren değişikliğinden önce yeni işin mevcut izin kapsamında olup olmadığı veya yeni bir izin gerekip gerekmediği kontrol edilmelidir.$q$, 6),
('calisma-vizesi', 'Çalışma vizesi ile ailemi de yanıma götürebilir miyim?', $q$Bazı ülkeler çalışma vizesi veya çalışma amaçlı oturum izni sahiplerinin eş ve çocukları için aile birleşimi veya bağımlı aile üyesi kapsamında başvuru yapmasına izin verebilir. Bunun şartları çalışanın statüsüne, gelirine, oturum süresine ve ülkenin mevzuatına göre değişebilir.$q$, 7),
('calisma-vizesi', 'Çalışma vizesi ile ülkede ne kadar süre kalabilirim?', $q$Çalışma vizesinin veya buna bağlı oturum izninin süresi çalışma sözleşmesine, çalışma iznine ve başvurulan ülkenin mevzuatına göre belirlenebilir. Çalışma ilişkisinin devam etmesi halinde iznin uzatılması veya yeni bir izin alınması gerekebilir.$q$, 8),
('calisma-vizesi', 'İş sözleşmem sona ererse çalışma vizem ne olur?', $q$İş sözleşmesinin sona ermesi, çalışma izninin veya buna bağlı oturum hakkının koşullarını etkileyebilir. Bazı ülkeler iş aramak veya yeni bir işverene geçmek için belirli bir süre tanırken, bazı durumlarda izin sona erebilir. Bu nedenle iş ilişkisinin sona ermesi halinde ülkenin ilgili makamlarının güncel kuralları kontrol edilmelidir.$q$, 9),
('calisma-vizesi', 'Çalışma vizesi başvurum reddedilirse tekrar başvurabilir miyim?', $q$Ret kararından sonra yeniden başvuru yapılabilmesi veya karara itiraz edilmesi, başvurulan ülkenin prosedürlerine ve ret gerekçesine göre değişebilir. Yeni bir başvuru yapılacaksa önceki ret kararında belirtilen sorunların dikkatle incelenmesi ve mümkün olduğunca giderilmesi önemlidir.$q$, 10),
('calisma-vizesi', 'Çalışma vizesi ile başka bir ülkede çalışabilir miyim?', $q$Hayır. Bir ülke tarafından verilen çalışma vizesi veya çalışma izni, başka bir ülkede otomatik olarak çalışma hakkı sağlamaz. Başka bir ülkede çalışmak için o ülkenin kendi çalışma ve göç kurallarına göre ayrıca izin veya vize alınması gerekir.$q$, 11),
('calisma-vizesi', 'Çalışma vizesi ile çalışırken eğitim alabilir miyim?', $q$Bu durum ülkenin mevzuatına ve sahip olduğunuz oturum veya çalışma statüsüne göre değişebilir. Bazı ülkeler çalışanların belirli eğitim programlarına katılmasına izin verirken, bazı eğitim türleri için ayrıca öğrenci statüsü veya izin gerekebilir.$q$, 12),
('calisma-vizesi', 'Çalışma vizesiyle kalıcı oturum alabilir miyim?', $q$Bazı ülkelerde belirli süre boyunca yasal olarak çalışmak ve diğer şartları karşılamak, uzun vadede kalıcı oturum veya benzeri bir statüye başvurma imkânı sağlayabilir. Ancak bu otomatik bir hak değildir; gerekli çalışma süresi, gelir, dil, entegrasyon ve diğer koşullar ülkeye göre değişir.$q$, 13);
