-- ============================================================
-- VISA TYPE FAQS — "Vize Türleri" dökümanlarından güncelleme
--
-- Her vize türü sayfasının SSS bloğunu, kurum tarafından
-- hazırlanan "Vize Türleri" dökümanlarındaki sorularla
-- değiştirir. /vize-turleri ana sayfasının SSS'leri (page_key
-- 'vize-turleri') bu migration'da DEĞİŞTİRİLMEZ.
--
-- Idempotent: ilgili page_key'ler önce silinir, bu yüzden
-- tekrar çalıştırmak satırları çoğaltmaz. Ancak ilk çalıştırma
-- sonrası admin panelinden yapılan düzenlemeler kaybolur —
-- yalnızca bir kez çalıştırın.
-- ============================================================
BEGIN;

DELETE FROM visa_type_faqs WHERE page_key IN (
  'turistik-vize',
  'ticari-vize',
  'aile-ziyareti-vizesi',
  'transit-vize',
  'fuar-kulturel-etkinlik-konferans-vizesi',
  'aile-birlesimi-vizesi',
  'ogrenci-vizesi',
  'calisma-vizesi'
);

INSERT INTO visa_type_faqs (page_key, question, answer, sort_order) VALUES

-- ---------- Turistik Vize ----------
('turistik-vize', $q$Vize başvurumu seyahat tarihinden ne kadar önce yapmalıyım?$q$, $q$Genellikle en az 1 ay önce planlanması önerilir. Randevu yoğunlukları ülkeye göre değiştiğinden, özellikle yoğun sezonda çok daha erken hareket etmek gerekir.$q$, 0),
('turistik-vize', $q$Pasaportumun süresi ne kadar olmalı?$q$, $q$Çoğu ülke, planlanan seyahat dönüş tarihinden itibaren pasaportunuzun en az 3 ila 6 ay daha geçerli olmasını ve boş sayfalarının bulunmasını şart koşar.$q$, 1),
('turistik-vize', $q$Başvuru için kesin uçak bileti almak zorunda mıyım?$q$, $q$Birçok ülke başvuru aşamasında kesin satın alınmış bilet yerine uçuş rezervasyonunu kabul eder. Böylece bilet masrafını riske atmamış olursunuz.$q$, 2),
('turistik-vize', $q$Bankada ne kadar param olmalı ve para ne kadar süredir içeride olmalı?$q$, $q$Sabit bir rakam yoktur; seyahat masraflarınızı karşılayacak düzeyde olmalıdır. Konsolosluklar hesap geçmişine baktığı için, başvuruya günler kala hesaba yatırılan ani ve yüklü paralar risk oluşturabilir; paranın hesaptaki varoluş süreci önemlidir.$q$, 3),
('turistik-vize', $q$Çalışmıyorum (öğrenciyim, ev hanımıyım vb.), nasıl başvuru yapabilirim?$q$, $q$Düzenli bir geliriniz veya iş yeriniz yoksa, seyahat masraflarınızı karşılayacak birinci derece bir yakınınızı (anne, baba, eş vb.) sponsor gösterebilirsiniz. Bu durumda sponsorun mali ve mesleki belgeleri dosyaya eklenmelidir.$q$, 4),
('turistik-vize', $q$Freelancer'ım veya serbest çalışıyorum, düzenli maaş bordrom yok. Nasıl başvuru yapabilirim?$q$, $q$Geleneksel bir maaş bordronuz olmasa da serbest meslek gelirinizi belgeleyebilirsiniz. Şirketiniz varsa vergi levhası ve faaliyet belgesi; yoksa freelance çalıştığınızı gösteren sözleşmeler, düzenli banka para akışları ve faturalar mesleki durumunuzu kanıtlamak için sunulabilir.$q$, 5),
('turistik-vize', $q$Daha önce vize reddi aldım, yeni başvurumu etkiler mi?$q$, $q$Önceki red otomatik olarak yeni red demek değildir. Ancak ilk başvurudaki eksiklikler (yetersiz bakiye, zayıf bağlar) giderilmeden aynı hatayla tekrar başvurmak olumsuz sonuç doğurabilir.$q$, 6),
('turistik-vize', $q$Tek girişli ve çok girişli vize arasındaki fark nedir?$q$, $q$Tek girişli vize ilgili ülkeye yalnızca bir kez girmenize izin verirken; çok girişli (multiple) vize, süresi içinde birden fazla giriş-çıkış yapmanıza olanak tanır.$q$, 7),
('turistik-vize', $q$Turistik vize ile ailemi veya arkadaşlarımı ziyaret edebilir miyim?$q$, $q$Evet, kısa süreli ziyaretler turistik kapsamda değerlendirilebilir; ancak bazı ülkeler ek olarak davetiye veya konaklama detaylarını gösteren belge talep edebilir.$q$, 8),
('turistik-vize', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez.$q$, 9),

-- ---------- Ticari Vize ----------
('ticari-vize', $q$Ticari vize başvurusu için resmi davetiye şart mı?$q$, $q$Evet, ticari vizelerin en kritik unsuru hedef ülkedeki firmadan gelen resmi davetiyedir. Davetiyede seyahat tarihleri, ziyaretin amacı ve masrafların kimin tarafından karşılanacağı net bir şekilde belirtilmelidir.$q$, 0),
('ticari-vize', $q$Davetiye orijinal mi olmalı, yoksa e-posta ile gelen taranmış kopya yeterli mi?$q$, $q$Çoğu konsolosluk ilk aşamada taranmış/e-posta yoluyla iletilen davetiyeleri (PDF) kabul eder. Ancak bazı ülkeler veya konsolosluklar nadiren de olsa orijinal ıslak imzalı davetiye veya kargo ile gelen belgeyi talep edebilir. Başvurulacak ülkenin güncel prosedürü kontrol edilmelidir.$q$, 1),
('ticari-vize', $q$Şirket sahibi veya tek ortaklı bir şirketim varsa, kendi kendime görevlendirme yazısını nasıl yazmalıyım?$q$, $q$Şirket sahibi ya da ortağıysanız, şirketinizin antetli kağıdına yine kendi imzanızla (şirket yetkilisi unvanıyla) seyahat amacınızı, tarihlerini, masrafların şirket veya şahsınız tarafından karşılanacağını ve seyahat sonrası işinizin başına döneceğinizi taahhüt eden bir beyan yazmanız gerekir.$q$, 2),
('ticari-vize', $q$Seyahat masraflarımı Türkiye'deki şirketim karşılayacaksa hangi belgeler gerekir?$q$, $q$Masraflar şirket tarafından karşılanacaksa, şirketin antetli kağıdına yazılmış resmi bir görevlendirme dilekçesi, şirket imza sirküleri, vergi levhası, faaliyet belgesi ve şirketin yeterli finansal güce sahip olduğunu gösteren banka hesap dökümleri dosyaya eklenmelidir.$q$, 3),
('ticari-vize', $q$Seyahat masraflarımı karşı taraftaki (davet eden) yabancı şirket karşılayacaksa ne yapmalıyım?$q$, $q$Davet eden yabancı firmanın, masrafları (uçak, konaklama vb.) üstleneceğini resmi davetiyede açıkça beyan etmesi gerekir. Ayrıca bazı ülkeler (örneğin Almanya gibi) davet eden firmanın kendi ülkesindeki yerel makamlardan resmi taahhütname almasını talep edebilir.$q$, 4),
('ticari-vize', $q$Şirket sahibi olmak ile şirket çalışanı olmak arasında başvuru belgeleri açısından ne fark vardır?$q$, $q$Şirket sahipleri/ortakları kendi şirketlerinin imza sirkülerini, vergi levhasını ve faaliyet belgesini sunarken; çalışanlar bunlara ek olarak şirketten alınmış ıslak imzalı görevlendirme yazısı, SGK tescil ve hizmet dökümü ile son aylara ait maaş bordrolarını ibraz etmek zorundadır.$q$, 5),
('ticari-vize', $q$Ticari vize ile makine montajı, teknik servis veya kurulum için gidiyorsam özel bir belge gerekir mi?$q$, $q$Evet. Seyahatinizin amacı toplantı değil de teknik servis, bakım veya makine kurulumu ise standart davetiyeler yetersiz kalabilir. Bu durumda iki şirket arasındaki hizmet/satış sözleşmesini ve işin mahiyetini gösteren ek teknik belgeleri sunmanız gerekir; bazı ülkeler bu tür görevler için kısa süreli çalışma izni prosedürü uygulayabilir.$q$, 6),
('ticari-vize', $q$Birden fazla ülkede iş toplantım veya fuarım varsa, başvuruyu hangi konsolosluğa yapmalıyım?$q$, $q$Birden fazla ülkeyi kapsayan iş seyahatlerinde, seyahat süresinin en uzun olduğu veya en kritik iş görüşmesinin gerçekleştirileceği ülkenin konsolosluğuna başvurulmalıdır. Süreler ve faaliyet yoğunluğu eşitse, seyahat rotasındaki ilk giriş yapacağınız ülkenin konsolosluğu yetkilidir.$q$, 7),
('ticari-vize', $q$Şahıs şirketi (şahıs firması) sahibiyim, şirket evraklarım limited veya anonim şirketlerden farklı mı?$q$, $q$Evet, farklıdır. Şahıs şirketlerinde tüzel kişilik bulunmadığı için Limited veya Anonim şirketlerdeki faaliyet belgesi ve imza sirküleri yerine; güncel vergi levhası, ilgili meslek odası veya esnaf sicil kayıt belgesi, noter onaylı imza beyannamesi ve şahsi ticari hesap dökümleri sunulur.$q$, 8),
('ticari-vize', $q$Ticari vize ile turistik seyahat yapabilir miyim?$q$, $q$Ticari vizenin ana amacı iş faaliyetleridir; ancak genellikle bu vizelerle seyahat süresi içinde kısa turistik geziler de yapılabilir. Fakat seyahatin ağırlıklı odak noktası iş olmalı ve ilk giriş gerekçesi ticari faaliyetlere dayanmalıdır.$q$, 9),
('ticari-vize', $q$Ticari vize ile hedef ülkede çalışabilir miyim veya iş arayabilir miyim?$q$, $q$Hayır. Ticari vize size o ülkede kalıcı olarak çalışma, yerel bir şirkette bordrolu işe başlama veya uzun süreli ticari faaliyet yürütme hakkı vermez. Yalnızca geçici iş görüşmeleri, toplantılar ve fuar katılımı içindir.$q$, 10),
('ticari-vize', $q$Fuara katılımcı veya ziyaretçi olarak gidiyorsam hangi belgeler gerekir?$q$, $q$Şirket ziyaretinden farklı olarak, katılacağınız uluslararası fuarın biletleri, online kayıt belgeleri, fuar standı kiralandıysa ilgili sözleşmeler veya fuar organizatöründen alınan resmi davetiyeler dosyanın merkezinde yer almalıdır.$q$, 11),
('ticari-vize', $q$Ticari vizeyle çok girişli (multiple) kalış hakkı almak için ne gerekiyor?$q$, $q$Bu tamamen konsolosluğun takdirine ve iş seyahatlerinizin sıklığına bağlıdır. Daha önce alınmış ticari vizeler, karşı firmadan gelen ve yıl içinde düzenli toplantı/projelerin olacağını belirten uzun süreli davetiyeler, çok girişli vize alma şansını önemli ölçüde artırır.$q$, 12),
('ticari-vize', $q$Daha önce aynı ülkeden turistik vize almış olmam ticari başvuru sürecini etkiler mi?$q$, $q$Daha önce sorunsuz seyahat edilmiş ve ülkenin kurallarına uyulmuş turistik vizeler, konsolosluk gözünde "güvenilir yolcu" profili oluşturduğu için ticari başvurularda olumlu bir referans teşkil edebilir.$q$, 13),
('ticari-vize', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez.$q$, 14),

-- ---------- Aile Ziyareti Vizesi ----------
('aile-ziyareti-vizesi', $q$Aile ziyareti vizesi için resmi davetiye şart mı?$q$, $q$Evet, aile ziyareti vizelerinin en temel dayanağı karşı taraftan gelen resmi davetiyedir. Davetiyede seyahat tarihleri, ziyaretin gerekçesi, konaklama adresi ve masrafların kimin tarafından üstlenileceği net olarak yer almalıdır.$q$, 0),
('aile-ziyareti-vizesi', $q$Davetiye hangi formatta olmalıdır (belediye onaylı mı, normal dilekçe mi)?$q$, $q$Bu durum ülkeye göre değişir. Örneğin Almanya gibi bazı Schengen ülkeleri yabancılar şubesinden (Ausländerbehörde) alınmış resmi "Verpflichtungserklärung" (taahhütname) talep ederken; bazı ülkeler ev sahibinin imzaladığı serbest metinli bir davetiyeyi ve kimlik fotokopisini yeterli bulur.$q$, 1),
('aile-ziyareti-vizesi', $q$Otel rezervasyonum yok, akrabamın evinde kalacağım. Konsolosluk otel rezervasyonu ister mi ve ev sahibi hangi evrakları sunmalıdır?$q$, $q$Hayır, aile ziyaretlerinde otel rezervasyonu zorunlu değildir. Ancak ev sahibinin o evde yasal olarak barındığını kanıtlayan tapu veya kira kontratı ile evin büyüklüğünün misafir ağırlamaya uygun olduğunu gösteren resmi ikamet belgeleri dosyaya eklenmelidir.$q$, 2),
('aile-ziyareti-vizesi', $q$Akrabalık bağını resmi olarak nasıl kanıtlamalıyım?$q$, $q$Türkiye'den yapılan başvurularda, e-Devlet üzerinden alınan Tam Vukuatlı Nüfus Kayıt Örneği (aile ve kök bilgileri içeren) akrabalık bağını kanıtlamak için en önemli belgedir. Akrabalık bağı zayıf veya arkadaş bazlı ise bu durum davet yazısında açıkça belirtilmelidir.$q$, 3),
('aile-ziyareti-vizesi', $q$Seyahat masraflarımı yurt dışındaki ev sahibim (sponsorum) karşılayacaksa ne yapmalıyım?$q$, $q$Masraflar yurt dışındaki kişi tarafından karşılanacaksa; davet eden kişinin resmi makamlardan aldığı taahhütnameyi, son gelir/maaş bordrolarını ve banka dökümlerini başvuru dosyasına eklemesi gerekir.$q$, 4),
('aile-ziyareti-vizesi', $q$Davet eden kişinin geliri veya çalışma statüsü (örneğin öğrenci olması) yetersizse ne olur?$q$, $q$Konsolosluklar, davet eden kişinin o ülkede geçimini sağlayabilecek düzenli bir gelire veya sosyal güvenceye sahip olmasını bekler. Eğer ev sahibi öğrenciyse veya geliri düşükse masrafları karşılayamayacağı için vize reddi riski doğar; bu durumda başvuran kendi mali durumunu (kendi banka hesabını) öne çıkararak masrafları kendisi üstlenmelidir.$q$, 5),
('aile-ziyareti-vizesi', $q$Davet eden kişinin o ülke vatandaşlığı yoksa (oturum izniyle kalıyorsa) davet geçersiz mi olur?$q$, $q$Hayır, geçersiz olmaz. Davet eden kişinin o ülkede geçerli bir oturum iznine (çalışma izni, mavi kart, oturum kartı vb.) sahip olması yeterlidir. Vatandaş olması şart değildir; ancak oturum izninin seyahat süresini kapsayacak kadar güncel olması gerekir.$q$, 6),
('aile-ziyareti-vizesi', $q$18 yaş altı çocukla aile ziyaretine gidiyorsam veya çocuk tek başına seyahat edecekse hangi ek belge gerekir?$q$, $q$Çocuğun seyahat etmeyen diğer ebeveyni veya yasal vasisi varsa, noter onaylı muvafakatname (veli izin belgesi) sunulması zorunludur. Boşanmış ebeveynler söz konusu ise velayet belgesi ve çocuğun okul durumunu kanıtlayan güncel öğrenci belgesi de dosyaya eklenmelidir.$q$, 7),
('aile-ziyareti-vizesi', $q$Arkadaş ziyareti ile aile ziyareti vizesi arasında prosedür farkı var mı?$q$, $q$Temelde süreç aynıdır; ancak konsolosluklar aile bağını (birinci derece akrabalık) kanıtlamayı daha kolay bulurken, arkadaşlar arası ziyaretlerde taraflar arasındaki tanışıklık hikâyesini (eski fotoğraflar, ortak geçmiş) kanıtlayan ek açıklamalar isteyebilir.$q$, 8),
('aile-ziyareti-vizesi', $q$Ev sahibinin (davet edenin) hedef ülkedeki oturum ve gelir durumu vizeyi etkiler mi?$q$, $q$Evet, doğrudan etkiler. Davet eden kişinin o ülkede yasal oturum iznine veya vatandaşlığa sahip olması ve masrafları üstlenecekse yeterli düzenli gelire sahip olduğunu kanıtlaması konsolosluk için güven kriteridir.$q$, 9),
('aile-ziyareti-vizesi', $q$Aile ziyareti vizesi ile ne kadar süre kalabilirim?$q$, $q$Kısa süreli (C tipi) vizeler genellikle 90 günü aşmayan konaklamalara izin verir. Vizenizin geçerlilik süresi ve ülkede kalabileceğiniz maksimum gün sayısı, pasaportunuza basılan vize etiketinde açıkça belirtilir.$q$, 10),
('aile-ziyareti-vizesi', $q$Vize başvurumu seyahat tarihinden ne kadar önce yapmalıyım?$q$, $q$Genellikle en az 1 ay önce planlanması önerilir. Randevu yoğunlukları ve konsoloslukların inceleme süreleri mevsime göre değiştiğinden, özellikle tatil dönemlerinde çok daha erken hareket etmek gerekir.$q$, 11),
('aile-ziyareti-vizesi', $q$Daha önce vize reddi aldım, aile ziyareti başvurumu nasıl etkiler?$q$, $q$Önceki red otomatik olarak yeni red demek değildir. Ancak önceki reddin gerekçesi (yetersiz bakiye, zayıf geri dönüş bağı vb.) giderilmemişse aynı risk devam eder. Güçlü bir davetiye ve net bağlar önceki reddin etkisini azaltabilir.$q$, 12),
('aile-ziyareti-vizesi', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez.$q$, 13),

-- ---------- Transit Vize ----------
('transit-vize', $q$Her aktarmalı uçuş için transit vize almak zorunda mıyım?$q$, $q$Hayır, her aktarmalı uçuş için transit vize gerekmez. Transit vize zorunluluğu tamamen aktarma yapacağınız ülkenin politikasına, pasaport türünüze (Umuma Mahsus, Hususi vb.) ve havalimanı içinde kalıp kalmayacağınıza göre değişiklik gösterir.$q$, 0),
('transit-vize', $q$Havalimanı transit vizesi (Airside Transit) ile havalimanından dışarı çıkabilir miyim?$q$, $q$Hayır. Havalimanı transit vizesi size yalnızca uluslararası transit alanında (hava tarafında) bekleyerek uçak değiştirme hakkı verir. Havalimanı dışına çıkmak, şehre inmek veya otelde konaklamak isterseniz standart giriş vizesi almanız gerekir.$q$, 1),
('transit-vize', $q$Aynı havaalanında, aynı terminalde aktarma yaparsam yine de transit vize gerekir mi?$q$, $q$Birçok ülke, uluslararası transit bölgesinden dışarı çıkmadığınız ve bagajınız son noktaya kadar transfer olduğu durumlarda transit vize aramaz. Ancak bazı ülkeler (örneğin ABD, İngiltere veya bazı Avrupa ülkeleri) pasaportunuza bağlı olarak havalimanı içinde olsanız dahi transit vize talep edebilir.$q$, 2),
('transit-vize', $q$Farklı havayollarıyla ayrı ayrı bilet aldıysam (self-transfer) transit vize gerekir mi?$q$, $q$Evet, büyük ihtimalle gerekir. Ayrı bilet aldığınız durumlarda bagajınızı almak, pasaport kontrolünden geçerek ülkeye girmek ve yeniden check-in yaparak uçağa binmek zorunda kalırsınız. Bu senaryo "transit" olmaktan çıkıp ülkeye resmi giriş yapma anlamına geldiği için standart vize şarttır.$q$, 3),
('transit-vize', $q$Amerika (ABD) üzerinden başka bir ülkeye uçarken transit vizeye ihtiyacım var mı?$q$, $q$Evet. Amerika, havalimanı dışına çıkmayacak ve sadece uçak değiştirecek olsanız dahi Türk vatandaşları için transit vize (C1 vizesi) zorunluluğu uygular. ABD aktarmalı uçuşlarda bu kurala mutlaka dikkat edilmelidir.$q$, 4),
('transit-vize', $q$İngiltere (UK) aktarmalı uçuşlarda transit vize gerekiyor mu?$q$, $q$İngiltere üzerinden yapılan bazı aktarmalarda (Direct Airside Transit Visa - DATV veya Visitor in Transit) pasaport türünüze ve vize muafiyetlerinize bağlı olarak transit vize gerekebilir. Güncel kurallar ve istisnalar uçuş öncesi mutlaka kontrol edilmelidir.$q$, 5),
('transit-vize', $q$Birden fazla ülkede aktarma yaparsam, her biri için ayrı transit vize almam gerekir mi?$q$, $q$Evet. Seyahat rotanız birden fazla farklı ülkenin havalimanından aktarma yapmanızı gerektiriyorsa, transit rejim kuralları her ülke için ayrı ayrı değerlendirilir. Hangi ülkenin transit vize istediği biletleme öncesi tek tek kontrol edilmeli ve gerekirse ilgili ülkeler için ayrı transit vizeler alınmalıdır.$q$, 6),
('transit-vize', $q$Aktarma sürem çok uzunsa (geceleme gerekiyorsa veya havalimanı oteline geçeceksem) transit vize kuralları değişir mi?$q$, $q$Evet, değişir. Uzun süreli aktarmalarda (örneğin 12-24 saat) havalimanı oteline geçmek, terminal değiştirmek veya geceyi dışarıda geçirmek zorunda kalırsanız bu durum "havalimanı transit" kapsamından çıkar. Ülkenin ulusal sınırları içine gireceğiniz için standart kısa süreli vize (C tipi) almanız gerekebilir.$q$, 7),
('transit-vize', $q$Transit vize başvurusu için nihai varış ülkemin vizesi olmalı mı?$q$, $q$Evet, kesinlikle gereklidir. Transit geçeceğiniz ülkenin konsolosluğu, asıl gideceğiniz ülkeye yasal olarak girebileceğinizi (o ülkenin vizesine veya pasaport hakkına sahip olduğunuzu) görmek ister; aksi takdirde transit vize onaylanmaz.$q$, 8),
('transit-vize', $q$Transit vize ne kadar sürede çıkar ve ne kadar önce başvurmalıyım?$q$, $q$Transit vizeler genellikle standart turistik veya ticari vizelere göre daha kısa sürede sonuçlanır. Ancak olası uçuş aksaklıkları ve randevu yoğunlukları göz önünde bulundurularak, seyahat tarihinden en az 3-4 hafta önce başvurulması önerilir.$q$, 9),
('transit-vize', $q$Transit vize başvurum reddedilirse uçuşum ne olur?$q$, $q$Transit vize reddi almanız durumunda ilgili ülkeden yasal olarak geçiş yapamayacağınız için uçuşunuzu gerçekleştiremezsiniz. Bu nedenle uçak bileti satın almadan önce aktarma noktalarının transit vize kurallarını mutlaka incelemeniz gerekir.$q$, 10),
('transit-vize', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez.$q$, 11),

-- ---------- Fuar, Kültürel Etkinlik ve Konferans Vizesi ----------
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Fuar veya konferans vizesi başvurusu için resmi davetiye şart mı?$q$, $q$Evet, bu vize türünün temel dayanağı etkinliği düzenleyen organizatörden veya hedef ülkedeki kurumdan gelen resmi davetiye, kayıt belgesi ya da kabul mektubudur. Belgede katılımcının adı, etkinliğin tarihleri ve kapsamı net olarak yer almalıdır.$q$, 0),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Fuarı stant açarak mı yoksa sadece ziyaretçi olarak mı ziyaret ettiğim vizeyi etkiler mi?$q$, $q$Evet, doğrudan etkiler. Eğer fuara stant sahibi/katılımcı olarak gidiyorsanız stant kiralama sözleşmesi ve şirket görevlendirmeniz dosyaya eklenmelidir. Ziyaretçi olarak gidiyorsanız, fuar biletleri ve online kayıt onay belgeleri sunulmalıdır.$q$, 1),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Akademik bir konferansa konuşmacı (speaker) veya bildiri sahibi olarak katılıyorsam hangi ek belgeler gerekir?$q$, $q$Konferans organizatöründen gelen resmi kabul mektubu (acceptance letter), sunacağınız bildirinin özeti (abstract) ve üniversitenizden veya kurumunuzdan alınan resmi görevlendirme/destek yazısı dosyanın en kritik parçalarıdır.$q$, 2),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Masraflarım kurumum, üniversitem veya etkinlik organizatörü tarafından karşılanacaksa ne yapmalıyım?$q$, $q$Masraflar kurum veya organizatör tarafından üstlenilecekse; kurumun antetli kağıdına yazılmış resmi sponsorluk yazısı, bütçe karşılama taahhüdü ve ilgili kurumun mali evrakları başvuruya eklenmelidir.$q$, 3),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Kültürel veya sanatsal bir etkinlik için (sergi, konser, gösteri) hangi ek belgeler istenir?$q$, $q$Sanatsal etkinliklerde, etkinliğin yapılacağı mekânın resmi davet yazısı, sanatçının veya ekibin özgeçmişi, sergilenecek eserlerin listesi veya projenin kültürel iş birliği anlaşmaları dosyada yer almalıdır.$q$, 4),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Spor etkinlikleri veya turnuvalar için başvuran sporcu ve antrenörlerin hangi evrakları sunması gerekir?$q$, $q$İlgili spor federasyonundan veya kulüpten alınan resmi görevlendirme yazısı, turnuva organizasyon komitesinin resmi davetiyesi ve lisans belgeleri başvuru dosyasının temelini oluşturur.$q$, 5),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Fuar vizesi ile standart ticari vize arasında bir fark var mı?$q$, $q$İşleyiş olarak çok benzerdir; ancak fuar vizelerinde odak noktası şirketler arası genel ticari görüşmeler değil, doğrudan o fuarın tarihleri ve katılımcı statüsüdür. Davetiye ve kayıt belgeleri tamamen fuar odaklı hazırlanmalıdır.$q$, 6),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Konferans kabul mektubu veya fuar kayıt dekontu zorunlu mu?$q$, $q$Evet, zorunludur. Konsolosluklar seyahat amacının somut bir temele dayandığını görmek ister; bu yüzden fuara kayıt yapıldığını gösteren ödeme dekontu veya biletler ile konferans kabul mektubu başvuru dosyasında mutlaka bulunmalıdır.$q$, 7),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Etkinlik süresi ile vizenin geçerlilik süresi birebir aynı mı olur?$q$, $q$Genellikle hayır. Konsolosluklar etkinliğin günlerine ek olarak seyahat esnekliği tanıyacak şekilde (örneğin birkaç gün önce varış veya sonrasında kısa süreli turistik eklemelerle) vize süresi verebilir; ancak bu tamamen konsolosluğun takdirindedir.$q$, 8),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Vize başvurumu seyahat tarihinden ne kadar önce yapmalıyım?$q$, $q$Fuar ve konferanslar sabit tarihlerde gerçekleştiği ve bilet/otel masrafları önceden yapıldığı için, randevu yoğunlukları da göz önüne alınarak en az 4 ila 6 hafta önce başvuru planlanmalıdır.$q$, 9),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Daha önce vize reddi aldım, etkinlik başvurumu nasıl etkiler?$q$, $q$Önceki red otomatik olarak yeni red demek değildir. Ancak uluslararası bir fuara veya konferansa katılımın gerçekliği güçlü kanıtlarla (resmi davetiyeler, kurum desteği) desteklenirse önceki reddin yarattığı risk dengelenebilir.$q$, 10),
('fuar-kulturel-etkinlik-konferans-vizesi', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez.$q$, 11),

-- ---------- Aile Birleşimi Vizesi ----------
('aile-birlesimi-vizesi', $q$Aile birleşimi vizesi için temel dil yeterliliği (örneğin A1 sertifikası) şart mı?$q$, $q$Evet, Almanya gibi birçok Schengen ülkesi eş durumundan yapılacak aile birleşimi başvurularında temel düzeyde (genellikle A1 seviyesi) hedef ülke dilini bildiğinizi gösteren uluslararası geçerli bir sertifika (Goethe, ÖSD vb.) talep eder.$q$, 0),
('aile-birlesimi-vizesi', $q$Dil sınavından (A1 belgesinden) muaf olabileceğim istisnai durumlar var mı?$q$, $q$Evet, bazı istisnalar bulunur. Başvuran kişinin yükseköğrenim mezunu olması (bazı ülkelerde uyum potansiyeli yüksek görülerek), fiziksel/zihinsel sağlık sorunları nedeniyle dil öğrenemeyecek durumda olması veya sponsor eşin belirli meslek gruplarında (Mavi Kart, nitelikli uzman vb.) çalışıyor olması dil sınavından muafiyet sağlayabilir.$q$, 1),
('aile-birlesimi-vizesi', $q$Evlilik veya akrabalık bağını resmi olarak hangi belgelerle kanıtlamalıyım?$q$, $q$Uluslararası evlenme kayıt örneği (Formül B), tam vukuatlı nüfus kayıt örneği ve evlilik cüzdanının ilgili sayfalarının noter onaylı tercümeleri akrabalık bağını kanıtlamak için sunulması gereken temel resmi belgelerdir.$q$, 2),
('aile-birlesimi-vizesi', $q$Yurt dışındaki eşimin (sponsorun) geliri ve konutu vize onayını nasıl etkiler?$q$, $q$Doğrudan etkiler. Sponsorun, ailesini geçindirebilecek düzeyde düzenli bir gelire sahip olması, sosyal yardım almıyor olması ve ailenin yasal olarak yaşayabileceği büyüklükte (kişi başı metrekare kuralına uygun) konuta (kira kontratı veya tapu) sahip olması konsolosluk için en kritik onay kriteridir.$q$, 3),
('aile-birlesimi-vizesi', $q$Sponsor eşin oturum izninin türü (geçici mi, kalıcı mı) süreci nasıl etkiler?$q$, $q$Evet, etkiler. Sponsorun kalıcı oturum iznine (Niederlassungserlaubnis) veya Avrupa Mavi Kartı'na (Blue Card) sahip olması işlemleri hızlandırabilirken; geçici veya öğrenci/stajyer statüsünde oturum iznine sahip olanlar için gelir ve konut şartları çok daha katı kurallara bağlanır.$q$, 4),
('aile-birlesimi-vizesi', $q$18 yaş altı veya üstü çocuklar aile birleşimi ile ebeveynlerinin yanına gidebilir mi?$q$, $q$18 yaş altı reşit olmayan çocuklar için aile birleşimi süreçleri yasal hak olarak değerlendirilir. Ancak 18 yaşını doldurmuş reşit çocukların ebeveynleriyle birleşmesi yalnızca istisnai ve zorunlu özel durumlarda (bakıma muhtaçlık, ağır sağlık sorunları vb.) mümkündür.$q$, 5),
('aile-birlesimi-vizesi', $q$Daha önceki evliliğimden olan çocuğumu götürürken diğer ebeveynin izni (muvafakatname) gerekiyor mu?$q$, $q$Kesinlikle evet. Eğer çocuğun velayeti ortaksa veya diğer ebeveyndeyse, çocuğun yurt dışına yerleşmesine rıza gösterdiğini belirten noter onaylı ve apostilli muvafakatname (veli izin belgesi) sunulması yasal bir zorunluluktur.$q$, 6),
('aile-birlesimi-vizesi', $q$Çocuğum başvuru sırasında 18 yaş sınırındaydı, süreç uzarsa vize tehlikeye girer mi?$q$, $q$Evet, bu kritik bir risktir. Bazı ülkelerde çocuk 18 yaşına girdiği an başvuru hakkını kaybedebilir. Bu nedenle reşit olma sınırındaki çocuk başvurularında, sürecin başvuru tarihindeki yaşa göre mi yoksa karar tarihindeki yaşa göre mi işletildiği (yaş sınırı esnekliği) hedef ülkenin yasalarına göre çok dikkatli incelenmelidir.$q$, 7),
('aile-birlesimi-vizesi', $q$Aile birleşimi vizesi ile gittiğim ülkede yasal olarak çalışma hakkım var mı?$q$, $q$Evet. Birçok Avrupa ülkesinde aile birleşimi vizesiyle (veya oturum kartıyla) ülkeye giriş yapan kişilere doğrudan sınırsız çalışma hakkı veya serbest meslek icra etme hakkı tanınır.$q$, 8),
('aile-birlesimi-vizesi', $q$Konsoloslukta veya vize mülakatında dil sınavı veya entegrasyon mülakatı yapılıyor mu?$q$, $q$Evet. Bazı konsolosluklar başvuru esnasında veya sonrasında, çiftin evliliğinin gerçek olup olmadığını (evlilik mülakatı) ve temel iletişim kurup kuramadığını ölçmek için hedef dilde kısa bir mülakat gerçekleştirebilir.$q$, 9),
('aile-birlesimi-vizesi', $q$Aile birleşimi vizesi başvurusu ortalama ne kadar sürede sonuçlanır?$q$, $q$Standart vadelere göre oldukça uzun süren bir süreçtir. Evrakların hedef ülkedeki yabancılar dairesine (Ausländerbehörde) gitmesi ve yerel makamların onay vermesi nedeniyle süreç genellikle 3 ila 6 ay (bazı durumlarda daha uzun) sürebilmektedir.$q$, 10),
('aile-birlesimi-vizesi', $q$Nişanlılar aile birleşimi vizesine başvurabilir mi?$q$, $q$Doğrudan aile birleşimi adı altında değil, genellikle "Evlilik Amaçlı Vize" (Fiancé Visa / Eheschließung) kategorisinde başvurulur. Bu vize ile ülkeye gidilerek o ülkede yasal evlilik gerçekleştirilir ve ardından oturum iznine dönüştürülür.$q$, 11),
('aile-birlesimi-vizesi', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez.$q$, 12),

-- ---------- Öğrenci Vizesi ----------
('ogrenci-vizesi', $q$Öğrenci vizesi için üniversiteden veya kurumdan gelen kabul belgesi (acceptance letter) şart mı?$q$, $q$Evet, şarttır. Öğrenci vizesi başvurularının temel dayanağı, akredite bir eğitim kurumundan alınmış resmi kabul mektubu veya kayıt belgesidir. Kabul belgesi olmadan öğrenci vizesine başvurulamaz.$q$, 0),
('ogrenci-vizesi', $q$Bloke hesap (Sperrkonto) nedir ve hangi ülkeler zorunlu tutar?$q$, $q$Bloke hesap; Almanya gibi bazı ülkelerin, öğrencinin hedef ülkede geçimini (kira, gıda, yaşam masrafları) resmi olarak sağlayabildiğini kanıtlamak için adına açtırdığı ve her ay belirli bir miktar para çekmesine izin veren özel bir banka hesabıdır. Vize başvurusu öncesinde bu hesaba yıllık geçim tutarının yatırılması zorunludur.$q$, 1),
('ogrenci-vizesi', $q$Dil yeterlilik belgem yoksa, "şartlı kabul" (conditional admission) ile öğrenci vizesi alabilir miyim?$q$, $q$Evet, birçok ülke (örneğin Almanya) dil yeterliliği olmayan öğrencilere üniversite bünyesindeki dil kurslarına katılması şartıyla "şartlı kabul" verir ve bu kabulle dil kursu vizesine / öğrenci adaylığı vizesine başvurmanıza olanak tanır.$q$, 2),
('ogrenci-vizesi', $q$Öğrenci vizesi başvurusunda sağlık sigortası ibraz etmek zorunlu mu, hangi sigortalar kabul edilir?$q$, $q$Evet, zorunludur. Konsolosluklar, ülkeye giriş yaptığınız andan itibaren geçerli olan seyahat ve sağlık sigortasını ister. Almanya gibi bazı ülkelerde uzun süreli öğrenci kayıtları için ülkenin resmi kamu sağlık sigortası (GKV) veya onaylı özel öğrenci sigortaları (PKV) dosyanın en kritik parçasıdır.$q$, 3),
('ogrenci-vizesi', $q$Öğrenci vizesi ile hedef ülkede yasal olarak çalışabilir miyim (yarı zamanlı / part-time)?$q$, $q$Çoğu gelişmiş ülke, uzun süreli öğrenci vizesi sahiplerine yasal olarak yıl içinde belirli bir süre (örneğin yılda 120 tam gün veya 240 yarı gün gibi) yarı zamanlı çalışma hakkı tanır. Ancak bu hak ülkelere göre değişiklik gösterir.$q$, 4),
('ogrenci-vizesi', $q$Öğrenci vizesi ile ailemi (eşimi veya çocuğumu) yanımda götürebilir miyim?$q$, $q$Evet, ancak şartları oldukça katıdır. Birçok ülkede öğrencinin eşi ve çocuklarının gelebilmesi için sponsorun (öğrencinin) ek finansal kaynaklara (daha yüksek bloke hesap veya gelir) ve ailenin rahatça barınabileceği genişlikte bir konuta sahip olması şartı aranır.$q$, 5),
('ogrenci-vizesi', $q$Mezuniyet sonrasında ülkede kalıp iş arama izni (post-study work) veriliyor mu?$q$, $q$Birçok ülke, kendi üniversitelerinden mezun olan uluslararası öğrencilere mezuniyet sonrasında belirli bir süre (genellikle 6 ay ila 1,5-2 yıl arasında) tam zamanlı iş arama veya oturum iznini uzatma hakkı tanır.$q$, 6),
('ogrenci-vizesi', $q$Dil okulu öğrencileri için öğrenci vizesi süresi ve şartları farklı mı?$q$, $q$Evet. Sadece kısa veya orta süreli dil okuluna gidecek olanlar için bazen kısa süreli C tipi vize verilirken; uzun süreli dil eğitimi (6 aydan uzun) alacaklar için ulusal öğrenci vizesi prosedürleri uygulanır. Dil okullarında genellikle haftalık ders saati zorunluluğu (en az 18-20 saat) aranır.$q$, 7),
('ogrenci-vizesi', $q$Masraflarımı ailem veya üçüncü bir kişi karşılayacaksa hangi mali belgeler gerekir?$q$, $q$Eğer öğrenci kendi gelirine sahip değilse, birinci derece aile bireyleri sponsor olabilir. Sponsorun düzenli gelirini gösteren maaş bordroları, banka hesap dökümleri, tapu/kira gelirleri ve noter onaylı "masrafların tamamını üstleniyorum" taahhütnamesi dosyaya eklenmelidir.$q$, 8),
('ogrenci-vizesi', $q$Erasmus veya benzeri değişim programlarıyla giden öğrencilerin prosedürü nedir?$q$, $q$Erasmus ve değişim programlarında, hem Türkiye'deki üniversiteden alınan hibe/görevlendirme yazıları hem de karşı üniversiteden gelen resmi kabul mektubu kullanılır. Bu programlarda süreçler genellikle daha hızlı ve standartlaştırılmış olur.$q$, 9),
('ogrenci-vizesi', $q$Vize mülakatında veya niyet mektubunda (motivation letter) en çok neye dikkat edilir?$q$, $q$Konsolosluklar, öğrencinin bu eğitimi neden alacağını, kariyer hedefiyle nasıl bağdaştırdığını ve eğitim bittikten sonra kendi ülkesine geri dönüp dönmeyeceğini anlamak ister. Niyet mektubunda bu planın çok net ifade edilmesi gerekir.$q$, 10),
('ogrenci-vizesi', $q$Öğrenci vizesi başvurusu ortalama ne kadar sürede sonuçlanır?$q$, $q$Uzun süreli (D tipi) vizeler, evrakların hedef ülkedeki yerel kurumlara (yabancılar dairesi) gönderilip incelenmesi nedeniyle genellikle 6 ila 12 hafta (bazı yoğun dönemlerde daha uzun) sürebilmektedir. Bu nedenle başvurunun dönemin başlamasından çok önce yapılması şarttır.$q$, 11),
('ogrenci-vizesi', $q$Eğitim sürem uzarsa veya bölüm/okul değiştirirsem vizem ve oturum iznim ne olur?$q$, $q$Eğitim süresinin uzaması durumunda, hedef ülkedeki Yabancılar Dairesi'ne başvurarak geçerli bir akademik gerekçeyle oturum izninizi uzatmanız gerekir. Okul veya bölüm değişikliğinde ise resmi makamların bilgilendirilmesi zorunludur.$q$, 12),
('ogrenci-vizesi', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez. (Bloke hesap ücretleri red durumunda masraf kesilmeden iade edilir.)$q$, 13),

-- ---------- Çalışma Vizesi ----------
('calisma-vizesi', $q$Çalışma vizesi başvurusu için önceden iş teklifi (job offer) almış olmak şart mı?$q$, $q$Evet, standart çalışma vizelerinin temel dayanağı yurt dışındaki bir işverenden alınmış imzalı iş sözleşmesi veya resmi bağlayıcı iş teklifidir. İş teklifi olmadan doğrudan çalışma vizesine başvurulamaz (istisnai iş arama vizeleri hariç).$q$, 0),
('calisma-vizesi', $q$Diplomamın ve mesleki yeterliliğimin hedef ülkede geçerli olması (denklik) zorunlu mu?$q$, $q$Özellikle regüle edilmiş mesleklerde (mühendislik, doktorluk, hemşirelik, öğretmenlik vb.) diplomanın hedef ülkedeki ilgili makamlarca onaylanması (denklik / Anerkennung) yasal bir zorunluluktur.$q$, 1),
('calisma-vizesi', $q$İşverenin veya hedef ülkedeki iş bulma kurumunun (örneğin İş Ajansı) onayı gerekiyor mu?$q$, $q$Evet. Birçok ülke (örneğin Almanya), yerel işgücü piyasasını korumak amacıyla iş sözleşmesinin yerel yasalara ve taban maaş sınırlarına uygun olup olmadığını ilgili kurumlar (Bundesagentur für Arbeit vb.) aracılığıyla inceler ve onay verir.$q$, 2),
('calisma-vizesi', $q$Çalışma vizesi başvurusu için dil yeterliliği (örneğin Almanca veya İngilizce) şart mı?$q$, $q$Bu durum meslek dalına ve ülkeye göre değişir. IT veya uluslararası kurumsal pozisyonlarda genellikle ileri düzey İngilizce yeterli olurken; sağlık, eğitim veya müşteri odaklı yerel sektörlerde hedef ülkenin dilini (örneğin B1/B2 düzeyinde) belgelendirmek zorunludur.$q$, 3),
('calisma-vizesi', $q$Avrupa Mavi Kart (EU Blue Card) nedir ve kimler bu kapsamda çalışma vizesi alabilir?$q$, $q$Avrupa Mavi Kart; yüksek nitelikli üçüncü ülke vatandaşlarının AB üyesi ülkelerde çalışabilmesini kolaylaştıran özel bir oturum ve çalışma iznidir. Üniversite mezunu olmak ve belirli bir brüt yıllık maaş eşiğini yakalamak Mavi Kart alabilmek için temel şartlardır.$q$, 4),
('calisma-vizesi', $q$Çalışma vizesiyle gittiğimde eşim de hemen çalışabilir mi, yoksa onun için ek bir onay veya dil şartı var mı?$q$, $q$Genellikle evet; ana başvuran yüksek nitelikli bir pozisyonda (örneğin Mavi Kart ile) gidiyorsa, eşe de doğrudan sınırsız çalışma hakkı verilir. Ancak standart çalışma vizelerinde veya bazı ülkelerde eşin çalışabilmesi için yerel makamlardan ek izin alınması veya temel dil şartının sağlanması gerekebilir.$q$, 5),
('calisma-vizesi', $q$Şirketim beni 90 günden kısa süreliğine yurt dışındaki projeye gönderiyor; uzun süreli çalışma vizesi mi almalıyım yoksa ticari/iş vizesi yeterli olur mu?$q$, $q$Eğer seyahat 90 günü aşmıyor ve sadece geçici bir toplantı, montaj veya proje denetimi amacı taşıyorsa, uzun süreli D tipi çalışma vizesi yerine hedef ülkenin şartlarına göre kısa süreli (C tipi) iş/ticari vize veya özel kısa süreli hizmet vizesi alınır. Ancak fiilen orada bir kadroda çalışacaksanız D tipi şarttır.$q$, 6),
('calisma-vizesi', $q$Ülkeye gittikten sonra çalıştığım işten ayrılıp iş değiştirebilir miyim?$q$, $q$İlk aşamada çalışma vizeniz belirli bir işverene ve pozisyona bağlı olarak (bağlı çalışma izniyle) verilir. İş değiştirmek istediğinizde hedef ülkedeki Yabancılar Dairesi'nden izin almanız veya yeni iş sözleşmenizle oturum izninizi güncellemeniz gerekebilir.$q$, 7),
('calisma-vizesi', $q$Belirli bir maaş sınırı (asgari geçim veya kalifiye meslek maaş eşiği) aranıyor mu?$q$, $q$Evet. Konsolosluklar ve çalışma ajansları, teklif edilen maaşın o ülkedeki sektörel standartların altında kalmamasını ve devlet yardımı almadan geçinmeye yetecek düzeyde olmasını şart koşar.$q$, 8),
('calisma-vizesi', $q$Çalışma vizesi başvurusu ortalama ne kadar sürede sonuçlanır?$q$, $q$Uzun süreli (D tipi) çalışma vizeleri; evrakların hem konsoloslukta hem de hedef ülkedeki yerel yabancılar ve çalışma dairelerinde incelenmesi nedeniyle genellikle 4 ila 12 hafta (bazı durumlarda daha uzun) sürebilmektedir.$q$, 9),
('calisma-vizesi', $q$"İş arama vizesi" ile "doğrudan çalışma vizesi" arasında ne fark vardır?$q$, $q$Doğrudan çalışma vizesi halihazırda elinizde bir iş sözleşmesi varken alınır. İş arama vizesi (Chancenkarte vb.) ise elinizde iş teklifi olmadan, ülkeye gidip yerinde iş arayabilmeniz için belirli mesleki ve dil puanlarına göre verilen kısa/orta süreli bir vize türüdür.$q$, 10),
('calisma-vizesi', $q$Çalışma vizesi ile gittiğimde sosyal güvenlik ve sağlık sigortası süreçleri nasıl işler?$q$, $q$İş sözleşmeniz başladığı andan itibaren işvereniniz sizi o ülkenin resmi sosyal güvenlik sistemine (emeklilik, işsizlik sigortası) ve zorunlu sağlık sigortasına kaydettirmekle yükümlüdür.$q$, 11),
('calisma-vizesi', $q$Çalışma vizesi ile gittiğim ülkede ailemi (eşimi ve çocuklarımı) yanımda götürebilir miyim?$q$, $q$Evet. Çalışma vizesi sahipleri, yeterli konut şartını ve ailenin geçimini sağlayacak finansal geliri kanıtladıkları takdirde aile birleşimi yoluyla eş ve çocuklarını yanlarına getirme hakkına sahiptir. Hatta bazı nitelikli göçmenlik yasalarında aileyle birlikte aynı anda başvuru yapılabilmektedir.$q$, 12),
('calisma-vizesi', $q$Vize başvurum reddedilirse ödediğim ücretler iade edilir mi?$q$, $q$Hayır. Konsolosluk vize harçları ve başvuru merkezi hizmet bedelleri, başvuru sonucu olumsuz olsa bile iade edilmez.$q$, 13);

COMMIT;
